Compucom CCQA/src/objects/Contract_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>BSLA_Number__c</fullName>
        <label>BSLA #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BSLA__c</fullName>
        <label>BSLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center_Description__c</fullName>
        <label>Cost Center Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>Contract LineItems</relationshipLabel>
        <relationshipName>Contract_LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FCST_Fiscal_Year_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Fiscal Year List</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>Contract LineItems</relationshipLabel>
        <relationshipName>Contract_LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <formula>FCST_Contract__r.FCST_Q__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FCST Q#</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Description__c</fullName>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <label>Risk Factor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Contract LineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contract LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Description__c</fullName>
        <label>Contract Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Owner(UNUSED)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <label>FCST Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Contracts</relationshipLabel>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>FCST Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/FCST_Initial_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Contract_LineItem__c</fullName>
        <label>Contract LineItem</label>
        <referenceTo>Contract_LineItem__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Fiscal_Year_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Fiscal Year List</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Planning_Fiscal_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Fiscal Year</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Amount__c</fullName>
        <label>Fcst Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Risk Factor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>FCST Initial Forecast</label>
    <nameField>
        <label>FCST Initial Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Initial Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period_Id__c</fullName>
        <label>Fiscal Period Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Planning_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal_Planning_Year</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>FCST Planning Fiscal Years</relationshipLabel>
        <relationshipName>FCST_Planning_Fiscal_Years</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Label__c</fullName>
        <label>Long_Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <label>Period Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Label__c</fullName>
        <label>Short Label</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_Label__c</fullName>
        <label>Long_Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Label__c</fullName>
        <label>Short Label Unused Field</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/Test_FCST_Batch_To_Dwnld_ContractLine.cls
@istest
public class Test_FCST_Batch_To_Dwnld_ContractLine {
     testMethod static void testCase1(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
            
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =1;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            cli.BSLA_Number__c = '2020320';
            cli.Cost_Center__c = 'Test Cost Center';
            cli.Cost_Center_Description__c ='Test Descr';
            cli.Fcst_Revenue_Type__c = 'Test Rev';
            cli.BSLA__c = 'Test BSLA';
            insert cli;
              
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
            FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
              
              
              
          } 
     }
     testMethod static void testCase2(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =2;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
            Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            cli.BSLA_Number__c = '2020320';
            cli.Cost_Center__c = 'Test Cost Center';
            cli.Cost_Center_Description__c ='Test Descr';
            cli.Fcst_Revenue_Type__c = 'Test Rev';
            cli.BSLA__c = 'Test BSLA';
            insert cli;
              
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
              
             
            
        Test.stopTest();
          }
     }
      testMethod static void testCase3(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =3;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
            Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            cli.BSLA_Number__c = '2020320';
            cli.Cost_Center__c = 'Test Cost Center';
            cli.Cost_Center_Description__c ='Test Descr';
            cli.Fcst_Revenue_Type__c = 'Test Rev';
            cli.BSLA__c = 'Test BSLA';
            insert cli;
              
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
	 testMethod static void testCase4(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =4;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            cli.BSLA_Number__c = '2020320';
            cli.Cost_Center__c = 'Test Cost Center';
            cli.Cost_Center_Description__c ='Test Descr';
            cli.Fcst_Revenue_Type__c = 'Test Rev';
            cli.BSLA__c = 'Test BSLA';
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
            FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase5(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
            List<FCST_Contract__c> contrList = new List<FCST_Contract__c>();
            FCST_Contract__c contracts1 = new FCST_Contract__c();
            contracts1.Contract__c = 'TestData';
            contracts1.Contract_Owner__c = thisUser.Id;
            contracts1.FCST_Q__c = 'Q000-035';
            contracts1.Contract_Description__c = 'Demo45';
            contracts1.Opportunity__c = optList[0].Id;
            contrList.add(contracts1);
              
              if(contrList!=null && !contrList.isEmpty()){
                  insert contrList;
              }
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =5;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
            Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            cli.BSLA_Number__c = '2020320';
            cli.Cost_Center__c = 'Test Cost Center';
            cli.Cost_Center_Description__c ='Test Descr';
            cli.Fcst_Revenue_Type__c = 'Test Rev';
            cli.BSLA__c = 'Test BSLA';
            insert cli;
              
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            obj.Execute(NULL,contrList);
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase6(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =6;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase7(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =7;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase8(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =8;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase9(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =9;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase10(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =10;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     }
     testMethod static void testCase11(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =11;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
          }
     
}
    testMethod static void testCase12(){
         User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
          System.runAs(thisUser) {
               FCST_UTIL.InsertTriggerMappingFields();
         list<Contract_LineItem__c> contractlineitems = new list<Contract_LineItem__c>();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
               List<Account> acList = new List<Account>();
            for(Integer i=0;i<20;i++){
                Account ac = new Account();
                ac.Name = 'Account';
                acList.add(ac);
            }
            if(acList!=null && !acList.isEmpty()){
                insert acList;
            }
              List<Opportunity> optList = new List<Opportunity>();
            for(Integer i=0;i<20;i++){
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = acList[0].Id;
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                optList.add(opt);
            }
            if(optList!=null && !optList.isEmpty()){
                insert optList;
            }  
            FCST_Contract__c contracts = new FCST_Contract__c();
            contracts.Contract__c = 'TestData';
            contracts.Contract_Owner__c = thisUser.Id;
            contracts.FCST_Q__c = 'Q000-035';
            contracts.Contract_Description__c = 'Demo45';
            contracts.Opportunity__c = optList[0].Id;
            insert contracts;
              
             List<Planning_Version__c> plvList = new List<Planning_Version__c>();
            for(Integer i=0;i<20;i++){
                Planning_Version__c plv = new Planning_Version__c();
                plv.Name = '2019';
                // plv.Version_Status__c = 'Open (Admin)';
                plvList.add(plv);
            }
            insert plvList;
              
            List<Fiscal_Year_Planning__c> fypList = new List<Fiscal_Year_Planning__c>();
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.EndDate__c = endate;
            fyp.StartDate__c = srtDate;
            fypList.add(fyp);
            
            if(fypList!=null && !fypList.isEmpty()){
                insert fypList;
            }

            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            for(Integer i=1;i<12;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = 'FY2019P0'+i;
                fym.End_Date__c = endate;
                fym.Start_Date__c = srtDate;
                fym.Fiscal_Planning_Year__c = fypList[0].Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 12;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = srtDate;
                fym.Month_Number__c =12;
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
             Contract_LineItem__c cli = new Contract_LineItem__c();
            cli.FCST_Contract__c = contracts.Id;
            cli.Line_Description__c = 'testDesc';
            cli.Risk_Factor__c = 40;
            cli.FCST_Fiscal_Year_List__c = fypList[0].Id;
            insert cli;
         //  list<FCST_Initial_Forecast__c> FCSTinitialforecast = new list<FCST_Initial_Forecast__c>();   
              FCST_Initial_Forecast__c intFcst = new FCST_Initial_Forecast__c();
            intFCST.Name = 'TestInt';
            intFCST.Fcst_Amount__c = 20000;
            intFCST.FCST_Contract__c = contracts.Id;
            intFCST.FCST_Fiscal_Year_List__c = fypList[0].Id;
            intFCST.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
            intFCST.Contract_LineItem__c = cli.Id;
            intFCST.Planning_Version__c = plvList[0].Id;
          //  intFCST.FCST_Planning_Fiscal_Year__c= fymList[0].Id;
            insert intFCST;
              Test.startTest();

            FCST_HyperLinkUpload_Batch_Download obj = new FCST_HyperLinkUpload_Batch_Download('2019');
            DataBase.executeBatch(obj); 
            FCST_Batch_To_Dwnld_ContractLine obj23 = new FCST_Batch_To_Dwnld_ContractLine('2019');
            DataBase.executeBatch(obj23);
            
            FCST_Batch_ContractLine_Download obj223 = new FCST_Batch_ContractLine_Download('2019');
            DataBase.executeBatch(obj223);
              
        Test.stopTest();
          }
     
}
}