Compucom CCQA/src/objects/FCST_Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Revenue_Types__c</fullName>
        <label>FCST Revenue Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Product Model</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>FCST Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Product Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>FCST_Revenue_Type__c</fullName>
        <label>FCST Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Prod - Commodity</fullName>
                </value>
                <value>
                    <fullName>Prod - Enterprise</fullName>
                </value>
                <value>
                    <fullName>eXcell</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCSTBatchToHandleProductTrigger.cls
global with sharing class FCSTBatchToHandleProductTrigger implements Database.Batchable<sObject>,Database.Stateful{
    	
	string revenueTypeLabel;
	List<Product2> productlistVal;
	global FCSTBatchToHandleProductTrigger(List<Product2> productList) {
		 	
	   Mapping_Setting__c mapCustomObj=Mapping_Setting__c.getValues('FCST Mapping Data');
	    if(mapCustomObj <> null)
	    	revenueTypeLabel = mapCustomObj.Fcst_Revenue_Type__c;
	    
	    productlistVal = new List<Product2>();	
	    productlistVal.addAll(productList);
	}
	
	global Database.QueryLocator start(Database.BatchableContext bc) {
	       
		return Database.getQueryLocator('Select FCST_Revenue_Types__c,Product__r.'+revenueTypeLabel+'	 from FCST_Product_Model__c where Product__c IN:productlistVal'); 
    }
    
    global void execute(Database.BatchableContext bc, List<FCST_Product_Model__c> productModelListVal){
     	try{
	    	List<FCST_Product_Model__c> modelListCPMUpdate = new List<FCST_Product_Model__c>();
	    	
	    	if(productModelListVal!=null && productModelListVal.size()>0){
	    		for(FCST_Product_Model__c proObj:productModelListVal){
	    			String revenue='';
	    			if((Product2)proObj.getSObject('Product__r')!=null)
	    			   revenue=(String)proObj.getSObject('Product__r').get(revenueTypeLabel);
	    			
	    			proObj.FCST_Revenue_Types__c=revenue;
	    			modelListCPMUpdate.add(proObj);
	    		}
	    	}
    	
	      if(modelListCPMUpdate!=null && modelListCPMUpdate.size()>0)
	       update modelListCPMUpdate;
     		
     	}
        catch(Exception e) {
            System.debug('Exception Message '+e);
            System.debug('Exception Line Number: '+e.getLineNumber());
        
        }
	
    }
    
    global void finish(Database.BatchableContext bc){
    	
    }
}