Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Geo_Codes__c.object
<CustomObject>
    <label>Fcst Geo Codes</label>
    <nameField>
        <label>Fcst Geo Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Geo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_GeoCodes__c</fullName>
        <label>FCST GeoCodes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Program_Executive__c</fullName>
        <label>FCST_Program Executive</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_BusinessUnit__c</fullName>
        <label>Fcst_BusinessUnit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_SVC_YR1__c</fullName>
        <label>Opportunity SVC YR1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_TCV__c</fullName>
        <label>Opportunity TCV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_In_Months__c</fullName>
        <label>Term In Months</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transition_Date__c</fullName>
        <label>Transition Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/classes/TEST_FCST_Field_Mapping_AC_CLONED.cls
@isTest
public class TEST_FCST_Field_Mapping_AC_CLONED   {
    
    static testMethod void test_mappingV1(){
        Mapping_Setting__c m1 = new Mapping_Setting__c();
        m1.Name = 'FCST Mapping Data';
        m1.FCST_ProgramManager__c = 'fcst_program_manager__c';
        m1.Cost_Center__c = 'fcst_cost_center__c';
        m1.Geo__c = 'fcst_geo_codes__c';
        m1.Geo_Name__c = 'geo_name__c';
        m1.Fcst_Q__c= 'fcst_q__c';
        m1.Fcst_SalesRegion__c='fcst_account_region_vertical__c	';
        m1.Fcst_SubRegion__c='fcst_account_sub_region__c';
        m1.Fcst_CPM__c='fcst_cpm_region__c	';
        m1.Fcst_Revenue_Type__c='fcst_revenue_type__c';
        m1.Fcst_StartDate__c='fcst_start_date__c';
        m1.Fcst_EndDate__c='fcst_end_date__c';
        m1.FCST_Program_Executive__c = 'fcst_program_executive__c';
        m1.FCST_GeoCodes__c = 'fcst_geocodes__c';
        m1.Opportunity_TCV__c = 'deal_tcv__c';
        m1.Opportunity_SVC_YR1__c = 'amount';
        m1.Fcst_BusinessUnit__c = 'test_picklist__c';
        m1.Term_In_Months__c = 'deal_duration__c';
        m1.Transition_Date__c = 'closedate';
        insert m1;  
        
        
        FCST_Field_Mapping_AC_CLONED fm = new FCST_Field_Mapping_AC_CLONED();
        fm.oppAmountStr = 'OppStr';
        fm.getOppPicklist();
        fm.getOppDatePicklist();
        fm.getOppDecimalPicklist();
        fm.getAccPicklist();
        fm.save();
        fm.gotohomepage();
        fm.getOppNum();
        fm.getOpptName();
        fm.getOpptStrFlds();
        fm.getOpptPrds();
        fm.getProductStrFlds();
        fm.getAccLookupFlds();
        fm.getProgramEngineers();
        fm.getAccountGeoCodes();
        fm.getbusinessUnitPicklist();
        fm.getOppTCVPicklist();
        fm.getSVCDecimalPicklist();
        fm.getTermsMonth();
        fm.getTransDatePicklist();
        
    }
    
    static testMethod void test_mappingV2(){
        FCST_Field_Mapping_AC_CLONED fm = new FCST_Field_Mapping_AC_CLONED();
        fm.getOppDatePicklist();
        fm.save();
    }
    
    static testMethod void test_mappingV3(){
        Mapping_Setting__c m2 = new Mapping_Setting__c();
        m2.Name = 'FCST Mapping Data';
        m2.Cost_Center__c = '--None--';
        m2.Geo__c = '--None--';
        m2.Geo_Name__c = '--None--';
        m2.Fcst_SalesRegion__c='--None--';
        m2.Fcst_SubRegion__c='--None--';
        m2.Fcst_CPM__c='--None--';
        m2.Fcst_Revenue_Type__c='--None--';
        m2.Fcst_StartDate__c='--None--';
        m2.Fcst_EndDate__c='--None--';
        m2.Fcst_Q__c = '--None--';
        m2.FCST_GeoCodes__c = '--None--';
        m2.FCST_ProgramManager__c = '--None--';
        m2.FCST_Program_Executive__c = '--None--';
        m2.Opportunity_TCV__c = '--None--';
        m2.Opportunity_SVC_YR1__c = '--None--';
        m2.Fcst_BusinessUnit__c = '--None--';
        m2.Term_In_Months__c = '--None--';
        m2.Transition_Date__c = '--None--';
        insert m2;
        
        
        FCST_Field_Mapping_AC_CLONED fm = new FCST_Field_Mapping_AC_CLONED();
        fm.save();
    }
    
}