Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Geo_Codes__c.object
<CustomObject>
    <label>Fcst Geo Codes</label>
    <nameField>
        <label>Fcst Geo Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Geo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_BSLA__c</fullName>
        <label>FCST BSLA</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_GeoCodes__c</fullName>
        <label>FCST GeoCodes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Program_Executive__c</fullName>
        <label>FCST_Program Executive</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_BusinessUnit__c</fullName>
        <label>Fcst_BusinessUnit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_RecordType_Api__c</fullName>
        <label>Opportunity RecordType Api</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_SVC_YR1__c</fullName>
        <label>Opportunity SVC YR1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_TCV__c</fullName>
        <label>Opportunity TCV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_In_Months__c</fullName>
        <label>Term In Months</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transition_Date__c</fullName>
        <label>Transition Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA/src/classes/Mapping_Setting_UTIL.cls
public class Mapping_Setting_UTIL {
    public void mapSettingUTIL(){
        Mapping_Setting__c setting = new Mapping_Setting__c();
            setting.Name = 'FCST Mapping Data';
            setting.FCST_BSLA__c = 'fcst_bsla__c';
            setting.Cost_Center__c = 'fcst_cost_center__c';
            setting.Fcst_BusinessUnit__c = 'Test_Picklist__c';
            setting.Fcst_CPM__c = 'fcst_cpm_region__c';
            setting.Fcst_EndDate__c = 'fcst_end_date__c';
            setting.FCST_Program_Executive__c  = 'fcst_program_executive__c';
            setting.FCST_ProgramManager__c  = 'fcst_program_manager__c';
            setting.Fcst_SalesRegion__c  = 'fcst_account_region_vertical__c';
            setting.Fcst_StartDate__c  = 'fcst_start_date__c';
            setting.Fcst_SubRegion__c  = 'fcst_account_sub_region__c';
            setting.FCST_GeoCodes__c  = 'fcst_geocodes__c';
            setting.Fcst_Q__c  = 'fcst_q__c';
            setting.Fcst_Revenue_Type__c  = 'fcst_revenue_type__c';
            setting.Geo__c  = 'fcst_geo_codes__c';
            setting.Geo_Name__c  = 'geo_name__c';
            setting.Term_In_Months__c  = 'Deal_Duration__c';
            setting.Transition_Date__c  = 'CloseDate';
            setting.Opportunity_SVC_YR1__c='amount';
            setting.Opportunity_TCV__c='deal_tcv__c';
            setting.Opportunity_RecordType_Api__c = 'Division__c';
            insert setting;
    }
}