Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Automobile</fullName>
                </value>
                <value>
                    <fullName>Defense</fullName>
                </value>
                <value>
                    <fullName>Conglomerates</fullName>
                </value>
                <value>
                    <fullName>Investment Banking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Fcst_End_Date__c</fullName>
        <label>Fcst End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Start_Date__c</fullName>
        <label>Fcst Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Type__c</fullName>
        <label>Fcst Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Annuity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Renewal Annuity</fullName>
                </value>
                <value>
                    <fullName>Annuity Change</fullName>
                </value>
                <value>
                    <fullName>Project Change</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Product Commodity</fullName>
                </value>
                <value>
                    <fullName>Product Enterprise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partial_Shipments__c</fullName>
        <label>Partial Shipments</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/Test_MappingFieldUtility.cls
@isTest
public class Test_MappingFieldUtility {
    static testmethod void mfudata(){
        string orgid  = UserInfo.getOrganizationId();
        string datestring = string.valueOf(datetime.now()).replace(':','').replace('-','').replace(' ','');
        integer RandomInteger = integer.valueOf(math.random()*100000);
        string uniquename= orgid + datestring + RandomInteger;
        UserRole ur = new UserRole(Name = 'CEO');
        profile p=[select id from profile where name='Standard User'];
        User u=new user(Alias='StndUsr', Email=uniquename+'@testorg.com',EmailEncodingKey='UTF-8',LastName='test',LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US',ProfileId=p.id,UserRoleId=ur.id, TimeZonesidKey='America/Los_Angeles',
                        UserName=uniquename+'@testorg.com');
        
        insert u;
        System.runAs(u){
            sobject obj ;
            sobject Opportunity;
            //   Opportunity opp = new Opportunity(); 
            Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',

                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_code_test__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
            
            Opportunity opt = new Opportunity();
            opt.Name = 'Test Opportunity';
            opt.Partial_Shipments__c = 'Yes';
            opt.Fcst_Type__c = 'Project';
            opt.CloseDate=System.today();
            opt.Fcst_Start_Date__c = system.today();
            opt.StageName='Closed Won';
            opt.Fcst_End_Date__c = system.today();
          
            insert opt;
            
            test.startTest();
            MappingFieldUtility mfu= new MappingFieldUtility();
          //  mfu.getBusinessUnit();
          //  mfu.getBusinessUnit(Obj);
            mfu.getCPMRegion();
            mfu.getCPMRegion(Obj);
            mfu.getOpportunityDynamicFields();
            mfu.getProjectEndDate();
            mfu.getProjectEndDate(opt);
            mfu.getProjectStartDate();
            mfu.getProjectStartDate(opt);
            mfu.getRevenueType();
           // mfu.getRevenueType(opt);
            mfu.getSalesRegion();
            mfu.getSalesRegion(Obj);
            mfu.getSubRegion();
            mfu.getSubRegion(Obj);
            mfu.getQNum();
            mfu.getGeoNum();
            mfu.getProgramManager();
           // mfu.getQNum(opt);
            
            test.stopTest();
        }
        
    }
    static testmethod void mfudata1(){
        string orgid  = UserInfo.getOrganizationId();
        string datestring = string.valueOf(datetime.now()).replace(':','').replace('-','').replace(' ','');
        integer RandomInteger = integer.valueOf(math.random()*100000);
        string uniquename= orgid + datestring + RandomInteger;
        UserRole ur = new UserRole(Name = 'CEO');
        profile p=[select id from profile where name='Standard User'];
        User u=new user(Alias='StndUsr1', Email=uniquename+'@testorg.com',EmailEncodingKey='UTF-8',LastName='test',LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US',ProfileId=p.id,UserRoleId=ur.id, TimeZonesidKey='America/Los_Angeles',
                        UserName=uniquename+'@testorg.com');
        
        insert u;
        System.runAs(u){
            sobject obj;
            Opportunity opp = new Opportunity();
            Mapping_Setting__c setting1=new Mapping_Setting__c(name='FCST Mapping Data');
            insert setting1;
            
            test.startTest();
            MappingFieldUtility mfu= new MappingFieldUtility();
           // mfu.getBusinessUnit();
          //  mfu.getBusinessUnit(Obj);
            mfu.getCPMRegion();
            mfu.getCPMRegion(Obj);
            mfu.getOpportunityDynamicFields();
            mfu.getProjectEndDate();
            mfu.getProjectEndDate(Obj);
            mfu.getProjectStartDate();
            mfu.getProjectStartDate(Obj);
            mfu.getRevenueType();
            mfu.getRevenueType(opp);
            mfu.getSalesRegion();
            mfu.getSalesRegion(Obj);
            mfu.getSubRegion();
            mfu.getSubRegion(Obj);
            test.stopTest();
        }
    }
}