Compucom CCQA/src/objects/FCST_Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FCST Product Model</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>FCST Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Product Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCST_To_CleanModel.cls
global class FCST_To_CleanModel implements Database.Batchable<sObject>,Database.Stateful {
		
    public Set<Id> oppIdSetdelete{get;set;}
    
	global FCST_To_CleanModel(Set<Id> oppIdSet) {
		oppIdSetdelete = new Set<Id>();
		oppIdSetdelete.addAll(oppIdSet);
	}
	
	global Database.QueryLocator start(Database.BatchableContext bc) {
		if(oppIdSetdelete!=null && oppIdSetdelete.size()>0){
	      return Database.getQueryLocator('Select Id from FCST_Product_Model__c where Opportunity__r.Id IN:oppIdSetdelete');
	    }
	    else{
	      return null;
	    }  
    }
    
     global void execute(Database.BatchableContext bc, List<FCST_Product_Model__c> productModelList){
     	  try{
	     		if(productModelList!=null && productModelList.size()>0){
	     			delete productModelList;
	     		}
     		
		    }
	       catch(Exception e) {
	            System.debug('Exception Message '+e);
	            System.debug('Exception Line Number: '+e.getLineNumber());
	        }
     }
     
     global void finish(Database.BatchableContext bc){
     	
        
     }    
}