Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCST_VersionSchedule.cls
global class FCST_VersionSchedule implements Schedulable {
    global void execute(SchedulableContext sc){
        List<Planning_Version__c> plvList = [Select Id,Version_Status__c FROM Planning_Version__c WHERE Version_Status__c= 'Open (Admin)' LIMIT 1];
        
            if(plvList[0].Version_Status__c =='Open (Admin)'){
                plvList[0].Version_Status__c = 'Closed';
            }
               update plvList;   
         
    }
}