Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>IsAutoConvert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAutoConvert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Gap_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Gap Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OpenByInProgressVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OpenByInProgressVersion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Planning Versions</relationshipLabel>
        <relationshipName>FCST_Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCST_NextPlanningVersionOpen.cls
public class FCST_NextPlanningVersionOpen{
    //@future
    public static void updateStatus(set<Id> setPlanningVerisonIds){
        
        map<string,Planning_Version__c> mapRExistingVersion = new map<string,Planning_Version__c>();       
        for(Planning_Version__c p : [select Id,OpenByInProgressVersion__c,Name,SequenceNo__c,Planning_Version_Fiscal_Year__c from Planning_Version__c where Is_this_a_Gap_Planning_Version__c = false and Is_this_a_Budget_Planning_Version__c = false and SequenceNo__c >= 1 and  SequenceNo__c <= 12 limit 50000]){
            mapRExistingVersion.put(p.Planning_Version_Fiscal_Year__c+'-'+p.SequenceNo__c,p);            
        }
        map<Id,Planning_Version__c> mapNextPlanningVersion = new map<Id,Planning_Version__c>();
        for(Planning_Version__c  p : [select Id,OpenByInProgressVersion__c,Is_this_a_Gap_Planning_Version__c,Is_this_a_Budget_Planning_Version__c,SequenceNo__c,Version_Status__c,Planning_Version_Fiscal_Year__c from Planning_Version__c  where Is_this_a_Gap_Planning_Version__c = false and Is_this_a_Budget_Planning_Version__c = false and id IN: setPlanningVerisonIds]){
            
                Integer sno = Integer.valueOf(p.SequenceNo__c);sno++;
                Integer pyear = Integer.valueOf(p.Planning_Version_Fiscal_Year__c);
                if(sno == 13){sno=1;pyear++;}
                string key = pyear+'-'+sno;
                Planning_Version__c pp;
                if(mapRExistingVersion.containsKey(key))pp = mapRExistingVersion.get(key);
                if(pp<>null)mapNextPlanningVersion.put(p.id,pp);
        }
        if(mapNextPlanningVersion.size()>0){
            List<Planning_Version__c> lstP = new List<Planning_Version__c>();
            for(Id pId : mapNextPlanningVersion.keyset()){
                Planning_Version__c p = mapNextPlanningVersion.get(pId);
                p.Previous_Version__c = pId;
                p.Version_Status__c = 'Open (Admin)';
                p.OpenByInProgressVersion__c = false;
                p.IsAutoConvert__c = true;
              //  if(setInprogressVerisonIds.contains(pId))
                   // p.OpenByInProgressVersion__c = true;
                lstP.add(p);
            }
            if(Schema.sObjectType.Planning_Version__c.fields.Previous_Version__c.isUpdateable() &&
               Schema.sObjectType.Planning_Version__c.fields.Version_Status__c.isUpdateable() &&
               Schema.sObjectType.Planning_Version__c.fields.OpenByInProgressVersion__c.isUpdateable()){
                update lstP;
            }
        }
    }
}