Compucom CCQA Org 100919/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FCST_Account_Region_Vertical__c</fullName>
        <label>FCST Account Region / Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Account</fullName>
                </value>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Financial Services Vertical</fullName>
                </value>
                <value>
                    <fullName>GE</fullName>
                </value>
                <value>
                    <fullName>Partner Account (Spans Multiple Regions)</fullName>
                </value>
                <value>
                    <fullName>Partner Account - No Direct Sales</fullName>
                </value>
                <value>
                    <fullName>Protected Account – TechZone</fullName>
                </value>
                <value>
                    <fullName>Retail Vertical</fullName>
                </value>
                <value>
                    <fullName>TBD / Needs Review</fullName>
                </value>
                <value>
                    <fullName>Unassigned / Not a Target</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>VAR Partner &quot;Protected&quot; Account – Clearpath</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
                <value>
                    <fullName>Supplier Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_Account_Sub_Region__c</fullName>
        <label>FCST Account Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada East</fullName>
                </value>
                <value>
                    <fullName>Canada West</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>US - Central East</fullName>
                </value>
                <value>
                    <fullName>US - DC Region</fullName>
                </value>
                <value>
                    <fullName>US - North Central</fullName>
                </value>
                <value>
                    <fullName>US - North East</fullName>
                </value>
                <value>
                    <fullName>US - South Central</fullName>
                </value>
                <value>
                    <fullName>US - South East</fullName>
                </value>
                <value>
                    <fullName>US - Strategic Accounts</fullName>
                </value>
                <value>
                    <fullName>US - Western Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_CPM_Region__c</fullName>
        <label>FCST CPM_Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US-DC Area</fullName>
                </value>
                <value>
                    <fullName>US-Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>US-Midwest</fullName>
                </value>
                <value>
                    <fullName>US-Ohio Valley</fullName>
                </value>
                <value>
                    <fullName>US-South Central</fullName>
                </value>
                <value>
                    <fullName>US-Southeast</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Target</fullName>
                </value>
                <value>
                    <fullName>US-US Bank</fullName>
                </value>
                <value>
                    <fullName>CAN-Canada</fullName>
                </value>
                <value>
                    <fullName>CAN-BMO</fullName>
                </value>
                <value>
                    <fullName>CAN-Gov&apos;t of Ontario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Fcst_Rev_Rec_Revenue_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Fcst_12_Month_Duration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fcst 12 Month Duration</label>
        <type>Checkbox</type>
    </fields>
    <label>Fcst Rev Rec Revenue Type</label>
</CustomObject>

Compucom CCQA/src/objects/FCST_Revenue_Recognization_Product__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Date Unused Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offering Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>FCST Revenue Recognization Products</relationshipLabel>
        <relationshipName>FCST_Revenue_Recognization_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FCST Revenue Recognization Product</label>
    <nameField>
        <displayFormat>RRP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Revenue Recognization Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>FCST_Cost_Center__c</fullName>
        <label>FCST Cost Center</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Revenue_Type__c</fullName>
        <label>FCST Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Prod - Commodity</fullName>
                </value>
                <value>
                    <fullName>Prod - Enterprise</fullName>
                </value>
                <value>
                    <fullName>eXcell</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/Test_Fcst_RevRecognizationRules.cls
@isTest
public class Test_Fcst_RevRecognizationRules {
    static testMethod void productData(){
           Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',

                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_code_test__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
        
        Fcst_Rev_Rec_Revenue_Type__c revType = new Fcst_Rev_Rec_Revenue_Type__c();
        revType.Name = 'Prod - Commodity';
        revType.Fcst_12_Month_Duration__c = true;
        insert revType;
            Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                Family = 'Hosted Services',
                isActive = true
            );
            insert prod;
              
            
        FCST_Revenue_Recognization_Product__c revPrd = new FCST_Revenue_Recognization_Product__c();
        revPrd.Amount__c = 100;
        revPrd.Date_del__c = true;
      //  revPrd.Offering_Category__c = 'Hosted Services';
        revPrd.Product__c = prod.Id;
        revPrd.Period__c = 'M+4';
        revPrd.Product_Code__c = 'TestPrd';
        revPrd.Revenue_Type__c = 'Prod - Commodity';
        insert revPrd;
        FCST_RevRecognizationRules frevrec = new FCST_RevRecognizationRules();
        frevrec.intTotalVal = Integer.valueOf('100');
        frevrec.strMonths= 'Test1';
        frevrec.getCategeoryFields();
        frevrec.oppType= revPrd.Revenue_Type__c ;
        frevrec.getActiveProducts();
         frevrec.strPrd = prod.id;
        frevrec.getTermsMonths();
        List<FCST_RevRecognizationRules.WrapperTermsMonth> wtmList = new List<FCST_RevRecognizationRules.WrapperTermsMonth>();
        FCST_RevRecognizationRules.WrapperTermsMonth wtm = new FCST_RevRecognizationRules.WrapperTermsMonth('M+1','100%',String.valueOf(revPrd.Id));
        List<FCST_RevRecognizationRules.WrapperPeriod> wrpList = new List<FCST_RevRecognizationRules.WrapperPeriod>();
        FCST_RevRecognizationRules.WrapperPeriod wrpData = new FCST_RevRecognizationRules.WrapperPeriod('M+4',revPrd);
        wrpList.add(wrpData);
        wrpData.compareTo(wrpData);
        wrpData.rev = revPrd; 
        wtmList.add(wtm);
        FCST_RevRecognizationRules.WrapperRegime wrg = new FCST_RevRecognizationRules.WrapperRegime('Test2',2,wrpList);
        list<FCST_RevRecognizationRules.WrapperRegime> testWrapper = new list<FCST_RevRecognizationRules.WrapperRegime>();
        testWrapper.add(wrg);     
        frevrec.lstRegime = testWrapper;
        frevrec.lstWrapperTermsMonth = wtmList;
        frevrec.selProductId = 'TestPrd';
        frevrec.blnCheck = true;
        frevrec.getIsClassic();
        frevrec.save();
        FCST_RevRecognizationRules.getPicklistValues('Account','Industry');
        frevrec.getRevenuePlanning();
        frevrec.getRegimeCalculation();
        //frevrec.getProductFamilys();
        frevrec.getTotals();
        
        
        frevrec.getTotalVal();
        frevrec.customSave();
        
         PageReference pgf = Page.FCST_RevRecognizationRules;
            Test.setCurrentPage(pgf);
            
            pgf.getparameters().put('pageMessage','Test');
        
    }
    
        static testMethod void productData2(){
             Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',

                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_code_test__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
        Fcst_Rev_Rec_Revenue_Type__c revType = new Fcst_Rev_Rec_Revenue_Type__c();
        revType.Name = 'Prod - Commodity';
        revType.Fcst_12_Month_Duration__c = true;
        insert revType;
            Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                Family = 'Hosted Services',
                isActive = true
            );
            insert prod;
           
        
        FCST_RevRecognizationRules frevrec = new FCST_RevRecognizationRules();
        frevrec.intTotalVal = Integer.valueOf('100');
        frevrec.strMonths= 'Test1';
        frevrec.getCategeoryFields();
        frevrec.oppType= 'Prod - Commodity' ;
        frevrec.getActiveProducts();
         frevrec.strPrd = prod.id;
        frevrec.getTermsMonths();
        List<FCST_RevRecognizationRules.WrapperTermsMonth> wtmList = new List<FCST_RevRecognizationRules.WrapperTermsMonth>();
        FCST_RevRecognizationRules.WrapperTermsMonth wtm = new FCST_RevRecognizationRules.WrapperTermsMonth('M+1','test','');
       // FCST_RevRecognizationRules.WrapperTermsMonth wtm1 = new FCST_RevRecognizationRules.WrapperTermsMonth('M+1','100',String.valueOf(revPrd.Id));
        List<FCST_RevRecognizationRules.WrapperPeriod> wrpList = new List<FCST_RevRecognizationRules.WrapperPeriod>();
        FCST_RevRecognizationRules.WrapperPeriod wrpData = new FCST_RevRecognizationRules.WrapperPeriod('M+4',null);
        wrpList.add(wrpData);
        wrpData.compareTo(wrpData);
       // wrpData.rev = revPrd; 
        wtmList.add(wtm);
      //  wtmList.add(wtm1);

        FCST_RevRecognizationRules.WrapperRegime wrg = new FCST_RevRecognizationRules.WrapperRegime('Test2',2,wrpList);
        list<FCST_RevRecognizationRules.WrapperRegime> testWrapper = new list<FCST_RevRecognizationRules.WrapperRegime>();
        testWrapper.add(wrg);     
        frevrec.lstRegime = testWrapper;
        frevrec.lstWrapperTermsMonth = wtmList;
        frevrec.selProductId = 'TestPrd';
       
        frevrec.blnCheck = true;
        frevrec.getIsClassic();
        frevrec.save();
        FCST_RevRecognizationRules.getPicklistValues('Account','Industry');
        frevrec.getRevenuePlanning();
        frevrec.getRegimeCalculation();
        //frevrec.getProductFamilys();
        frevrec.getTotals();
        
        
        frevrec.getTotalVal();
        frevrec.customSave();
        
         PageReference pgf = Page.FCST_RevRecognizationRules;
            Test.setCurrentPage(pgf);
            
            pgf.getparameters().put('pageMessage','Test');
        }

           static testMethod void getData5(){
                Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',

                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_code_test__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
                FCST_RevRecognizationRules frevrec = new FCST_RevRecognizationRules();
               frevrec.oppType= 'Prod - Commodity' ;
                frevrec.strPrd = '--None--';
                frevrec.getTermsMonths();
               frevrec.getActiveProducts();
                frevrec.initmethod();
            }
       
    
}