Compucom CCQA Org 100919/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FCST_Account_Region_Vertical__c</fullName>
        <label>FCST Account Region / Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Account</fullName>
                </value>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Financial Services Vertical</fullName>
                </value>
                <value>
                    <fullName>GE</fullName>
                </value>
                <value>
                    <fullName>Partner Account (Spans Multiple Regions)</fullName>
                </value>
                <value>
                    <fullName>Partner Account - No Direct Sales</fullName>
                </value>
                <value>
                    <fullName>Protected Account – TechZone</fullName>
                </value>
                <value>
                    <fullName>Retail Vertical</fullName>
                </value>
                <value>
                    <fullName>TBD / Needs Review</fullName>
                </value>
                <value>
                    <fullName>Unassigned / Not a Target</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>VAR Partner &quot;Protected&quot; Account – Clearpath</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
                <value>
                    <fullName>Supplier Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_Account_Sub_Region__c</fullName>
        <label>FCST Account Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada East</fullName>
                </value>
                <value>
                    <fullName>Canada West</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>US - Central East</fullName>
                </value>
                <value>
                    <fullName>US - DC Region</fullName>
                </value>
                <value>
                    <fullName>US - North Central</fullName>
                </value>
                <value>
                    <fullName>US - North East</fullName>
                </value>
                <value>
                    <fullName>US - South Central</fullName>
                </value>
                <value>
                    <fullName>US - South East</fullName>
                </value>
                <value>
                    <fullName>US - Strategic Accounts</fullName>
                </value>
                <value>
                    <fullName>US - Western Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_CPM_Region__c</fullName>
        <label>FCST CPM_Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US-DC Area</fullName>
                </value>
                <value>
                    <fullName>US-Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>US-Midwest</fullName>
                </value>
                <value>
                    <fullName>US-Ohio Valley</fullName>
                </value>
                <value>
                    <fullName>US-South Central</fullName>
                </value>
                <value>
                    <fullName>US-Southeast</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Target</fullName>
                </value>
                <value>
                    <fullName>US-US Bank</fullName>
                </value>
                <value>
                    <fullName>CAN-Canada</fullName>
                </value>
                <value>
                    <fullName>CAN-BMO</fullName>
                </value>
                <value>
                    <fullName>CAN-Gov&apos;t of Ontario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Owner(UNUSED)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Contract_Created_Year__c</fullName>
        <label>FCST Baseline Created Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <label>FCST Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Geo_Name__c</fullName>
        <label>Fcst Geo Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Geo_Number__c</fullName>
        <label>Fcst Geo Number(UNUSED)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Contracts</relationshipLabel>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>FCST Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Geo_Codes__c.object
<CustomObject>
    <label>Fcst Geo Codes</label>
    <nameField>
        <label>Fcst Geo Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Geo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VISA</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Automobile</fullName>
                </value>
                <value>
                    <fullName>Defense</fullName>
                </value>
                <value>
                    <fullName>Conglomerates</fullName>
                </value>
                <value>
                    <fullName>Investment Banking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Fcst_End_Date__c</fullName>
        <label>Fcst End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Geo_Codes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fcst Geo Codes</label>
        <referenceTo>Fcst_Geo_Codes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Start_Date__c</fullName>
        <label>Fcst Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Text_QNum__c</fullName>
        <label>Fcst_Text_QNum</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/Test_FCST_Insert_Contract_Util.cls
@isTest
public class Test_FCST_Insert_Contract_Util {
    static testMethod void getContractData(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
             FCST_UTIL.InsertTriggerMappingFields();
             Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',
                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_codes__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
            
            
            
            Account ac = new Account();
            ac.Name = 'Test Account';
            insert ac;
            Fcst_Geo_Codes__c fgc  = new Fcst_Geo_Codes__c(name='test test1');
            insert fgc;
            List<Opportunity> optList = new List<Opportunity>();
            Opportunity opt = new Opportunity();
            opt.Name = 'test Oppt';
            opt.OwnerId = thisUser.Id;
            opt.AccountId = ac.Id;
            opt.StageName = 'Closed Won';
            opt.Fcst_Text_QNum__c = 'Q-44297';
            opt.CloseDate = System.today();
            opt.Fcst_Geo_Codes__c = fgc.id;
            optList.add(opt);
            
            if(optList!=NULL && !optList.isEmpty()){
                //insert optList;
            }
            
            FCST_Contract__c cont = new FCST_Contract__c();
            cont.Opportunity__c = optList[0].Id;
            cont.Fcst_Geo_Name__c = setting.geo_name__c;
            cont.Fcst_Geo_Number__c = 689;
            cont.FCST_Q__c = 'test' ;
            cont.FCST_Contract_Created_Year__c = String.valueOf(opt.CloseDate);
            cont.Contract_Owner__c = thisUser.Id;
            /* cont.Fcst_Geo_Name__c = 'geo name';
cont.Fcst_Geo_Number__c = 99999;
cont.FCST_Q__c = 'QData'; */     
           // insert cont;
            
            
            FCST_Insert_Contract_Util contrUtil = new FCST_Insert_Contract_Util();
            FCST_Insert_Contract_Util.createContracts(optList);
        }
    }
    static testMethod void getContractData2(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser) {
             FCST_UTIL.InsertTriggerMappingFields();
            Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',
                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_codes__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='division__c');
            insert setting;
            
            
            Account ac = new Account();
            ac.Name = 'Test Account';
            insert ac;
            
            List<Opportunity> optList = new List<Opportunity>();
            Opportunity opt = new Opportunity();
            opt.Name = 'test Oppt';
            opt.AccountId = ac.Id;
            opt.StageName = 'Closed Won';
            opt.Fcst_Text_QNum__c = setting.Fcst_Q__c;
            opt.CloseDate = System.today();
            optList.add(opt);
            
            if(optList!=NULL && !optList.isEmpty()){
                insert optList;
            }
            
            FCST_Contract__c cont = new FCST_Contract__c();
            cont.Opportunity__c = optList[0].Id;
            cont.Fcst_Geo_Name__c = 'geo_name__c';
            cont.Fcst_Geo_Number__c = 2000;
            cont.FCST_Q__c = setting.Fcst_Q__c;
            cont.FCST_Contract_Created_Year__c = String.valueOf(opt.CloseDate);
            // cont.Contract_Owner__c = thisUser.Id;
            /* cont.Fcst_Geo_Name__c = 'geo name';
cont.Fcst_Geo_Number__c = 99999;
cont.FCST_Q__c = 'QData'; */     
            insert cont;
            
            
            FCST_Insert_Contract_Util contrUtil = new FCST_Insert_Contract_Util();
            FCST_Insert_Contract_Util.createContracts(optList);
            FCST_Insert_Contract_Util.updateCPMRegionOfContract(optList);
        }
    }
}