Compucom CCQA Org 100919/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FCST_Account_Region_Vertical__c</fullName>
        <label>FCST Account Region / Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Account</fullName>
                </value>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Financial Services Vertical</fullName>
                </value>
                <value>
                    <fullName>GE</fullName>
                </value>
                <value>
                    <fullName>Partner Account (Spans Multiple Regions)</fullName>
                </value>
                <value>
                    <fullName>Partner Account - No Direct Sales</fullName>
                </value>
                <value>
                    <fullName>Protected Account – TechZone</fullName>
                </value>
                <value>
                    <fullName>Retail Vertical</fullName>
                </value>
                <value>
                    <fullName>TBD / Needs Review</fullName>
                </value>
                <value>
                    <fullName>Unassigned / Not a Target</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>VAR Partner &quot;Protected&quot; Account – Clearpath</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
                <value>
                    <fullName>Supplier Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_Account_Sub_Region__c</fullName>
        <label>FCST Account Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliances</fullName>
                </value>
                <value>
                    <fullName>Canada East</fullName>
                </value>
                <value>
                    <fullName>Canada West</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>US - Central East</fullName>
                </value>
                <value>
                    <fullName>US - DC Region</fullName>
                </value>
                <value>
                    <fullName>US - North Central</fullName>
                </value>
                <value>
                    <fullName>US - North East</fullName>
                </value>
                <value>
                    <fullName>US - South Central</fullName>
                </value>
                <value>
                    <fullName>US - South East</fullName>
                </value>
                <value>
                    <fullName>US - Strategic Accounts</fullName>
                </value>
                <value>
                    <fullName>US - Western Region</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FCST_CPM_Region__c</fullName>
        <label>FCST CPM_Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US-DC Area</fullName>
                </value>
                <value>
                    <fullName>US-Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>US-Midwest</fullName>
                </value>
                <value>
                    <fullName>US-Ohio Valley</fullName>
                </value>
                <value>
                    <fullName>US-South Central</fullName>
                </value>
                <value>
                    <fullName>US-Southeast</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Target</fullName>
                </value>
                <value>
                    <fullName>US-US Bank</fullName>
                </value>
                <value>
                    <fullName>CAN-Canada</fullName>
                </value>
                <value>
                    <fullName>CAN-BMO</fullName>
                </value>
                <value>
                    <fullName>CAN-Gov&apos;t of Ontario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Contract_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>BSLA__c</fullName>
        <label>BSLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU_Level1__c</fullName>
        <label>BU Level1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center_Description__c</fullName>
        <label>Cost Center Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <formula>FCST_Contract__r.FCST_Q__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FCST Q#</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contract LineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contract LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Contract__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <label>FCST Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>FCST Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>FCST Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fcst_Cost_Center__c.object
<CustomObject>
    <fields>
        <fullName>BSLA__c</fullName>
        <label>BSLA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>203563</fullName>
                </value>
                <value>
                    <fullName>10C363</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU_Level1__c</fullName>
        <label>BU Level1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BU_Level_2__c</fullName>
        <label>BU Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center_Description__c</fullName>
        <label>Cost Center Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fcst Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fcst Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Opportunity_Initial_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Revenue_Type__c</fullName>
        <formula>&apos;Consolidated Revenue&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FCST Revenue Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>FCST Opportunity Initial Forecast</label>
    <nameField>
        <label>FCST Oppy Initial Forecast  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Opportunity Initial Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SalesRegion__c</fullName>
        <label>Fcst_SalesRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_SubRegion__c</fullName>
        <label>Fcst_SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Name__c</fullName>
        <label>Geo Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Fcst_End_Date__c</fullName>
        <label>Fcst End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Geo_Codes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fcst Geo Codes</label>
        <referenceTo>Fcst_Geo_Codes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Start_Date__c</fullName>
        <label>Fcst Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fcst_Text_QNum__c</fullName>
        <label>Fcst_Text_QNum</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/Test_FCST_UpdateContractExtension.cls
@isTest
public class Test_FCST_UpdateContractExtension {
    static testMethod void contractData(){
             FCST_UTIL.InsertTriggerMappingFields();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
        
          Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',
                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_codes__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='fcst_q__c	');
            insert setting;
            
        
                 String qnum = 'Q000-035';
                Account ac = new Account();
                ac.Name = 'Account';
                insert ac;
        
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = ac.Id;
                opt.Fcst_Text_QNum__c = 'fcst_q__c';
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                insert opt;
        
        PageReference pgf = Page.FCST_Update_Contract;
            Test.setCurrentPage(pgf);
            
        pgf.getparameters().put('id',String.valueOf(opt.Id));
        
        List<Fcst_Cost_Center__c> costC = new List<Fcst_Cost_Center__c>();
        Fcst_Cost_Center__c costCentr = new Fcst_Cost_Center__c();
        costCentr.Name = '010A';
        costCentr.Cost_Center_Description__c = 'TestDataDESC';
        costCentr.BSLA__c = '203563';
        costCentr.BU_Level1__c = 'Corporate';
        costCentr.BU_Level_2__c = 'Corp';
        insert costCentr;
        costC.add(costCentr);
        
        Planning_Version__c plv = new Planning_Version__c();
        plv.Name = '2019-March';
        plv.Version_Status__c =  'Open (Admin)';
        insert plv;
        
        Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.StartDate__c = srtDate;
            fyp.EndDate__c = endate;
            insert fyp;
         
        List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
        for(Integer i=0;i<20;i++){
        Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
        fym.Short_Label__c = 'TestData';
        fym.Period_Number__c = 1;
        fym.Fiscal_Planning_Year__c = fyp.Id;
        fymList.add(fym);
        }
        
        if(fymList!=null && !fymList.isEmpty()){
            insert fymList;
        }
        
        Fiscal_Year_Model__c fym2 = new Fiscal_Year_Model__c();
        fym2.Short_Label__c = 'TestData2';
        fym2.Period_Number__c = 2;
        fym2.Fiscal_Planning_Year__c = fyp.Id;
        insert fym2;
        
       FCST_Contract__c contr = new FCST_Contract__c();
            contr.Fcst_Account__c = ac.Id;
            contr.Contract__c = 'TestContract';
            contr.Contract_Description__c = 'TestDescr';
           // contr.Contract_Owner__c = loginUser.id;
            contr.FCST_Contract_Created_Year__c = '2019';
            contr.Fcst_Geo_Name__c = 'geo name';
            contr.Fcst_Geo_Number__c = 99999;
            contr.FCST_Q__c = 'QData';
            contr.Opportunity__c = opt.Id;
            insert contr;
            
            Contract_LineItem__c contLineItem = new Contract_LineItem__c();
            contLineItem.FCST_Contract__c = contr.Id;
            contLineItem.FCST_Fiscal_Year_List__c = fyp.Id;
            contLineItem.Risk_Factor__c = 233;
            insert contLineItem;
        
        List<FCST_Initial_Forecast__c> intFcstList = new List<FCST_Initial_Forecast__c>();
        for(Integer i=0;i<20;i++){
        FCST_Initial_Forecast__c iniFcst = new FCST_Initial_Forecast__c();
        iniFcst.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
        iniFcst.FCST_Fiscal_Year_List__c = fymList[0].Fiscal_Planning_Year__c;
        iniFcst.Fcst_Amount__c = 0;
        iniFcst.Contract_LineItem__c = contLineItem.Id;
        iniFcst.FCST_Contract__c = contr.Id;
        iniFcst.Account__c = ac.Id;
        intFcstList.add(iniFcst);
        }
        if(intFcstList!=null && !intFcstList.isEmpty()){
            insert intFcstList;
        }
        
       // for(Fiscal_Year_Model__c fymm:fymList){
       /* FCST_Initial_Forecast__c iniFcst = new FCST_Initial_Forecast__c();
        iniFcst.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
        iniFcst.FCST_Fiscal_Year_List__c = fyp.Id;
        iniFcst.Fcst_Amount__c = 0;
        iniFcst.Contract_LineItem__c = contLineItem.Id;
        iniFcst.FCST_Contract__c = contr.Id;
        iniFcst.Account__c = ac.Id;
        insert iniFcst;*/
        // }

        FCST_Opportunity_Initial_Forecast__c oif = new FCST_Opportunity_Initial_Forecast__c();
        oif.Fcst_Fiscal_Period__c = fymList[0].Id;
        oif.Fcst_Weighted_Revenue__c = 84;
        oif.Fcst_Opportunity__c = opt.Id;
        oif.FCST_Planning_Version__c = plv.Id;
        oif.Fcst_Q__c =  opt.Fcst_Text_QNum__c;
        insert oif;
        
        FCST_Opportunity_Initial_Forecast__c oif2 = new FCST_Opportunity_Initial_Forecast__c();
        oif2.Fcst_Fiscal_Period__c = fym2.Id;
        oif2.Fcst_Weighted_Revenue__c = 1000;
        oif2.Fcst_Opportunity__c = opt.Id;
        oif2.FCST_Planning_Version__c = plv.Id;
        oif2.Fcst_Q__c =  opt.Fcst_Text_QNum__c;
        insert oif2;
        
       /* Fcst_Geo_Code__c geoCode = new Fcst_Geo_Code__c();
        geoCode.Name = 'fcst_geo_code__c';
        insert geoCode;*/
        
        ApexPages.StandardController std=new ApexPages.StandardController(opt);
        FCST_UpdateContractExtension  updContract = new FCST_UpdateContractExtension(std);
        FCST_UpdateContractExtension.WMonths months = new FCST_UpdateContractExtension.WMonths(2000,'Test');
        List<FCST_UpdateContractExtension.ContractLinewrapper> contLineWrpList = new List<FCST_UpdateContractExtension.ContractLinewrapper>();
        //FCST_UpdateContractExtension.ContractLinewrapper contrLine = new FCST_UpdateContractExtension.ContractLinewrapper('Test',contLineItem,intFcstList,true);
       // contLineWrpList.add(contrLine);
        FCST_UpdateContractExtension.Contractwrapper contrWrp = new FCST_UpdateContractExtension.Contractwrapper(contr,intFcstList,contLineWrpList);
        
        FCST_UpdateContractExtension.getOpportunityStage(String.valueOf(opt.Id));
        updContract.cfiscalyear = '2019';
        updContract.generateDynamicId();
        updContract.lineItemDuplicateValue();
        //updContract.costcentremethod();
        updContract.createInitialForecast(contr.Id,contLineItem.Id,ac.Id);
        updContract.getProduct();
        updContract.searchContract();
        updContract.getCostCentre();
        updContract.getFiscalYears();
        updContract.searchContract();
        updContract.getCostCentre();
        updContract.getOpportunityInitialTotal();
        updContract.lineItemInitialTotal();
        updContract.getBSLA();
        updContract.addContractLineItem();
        updContract.removeContractLineItem();
        updContract.RevertProduct();
        updContract.EditProduct();
        updContract.goBack();
        updContract.saveContract();

        }
    
    static testMethod void contractData2(){
             FCST_UTIL.InsertTriggerMappingFields();
            Date srtDate = date.newInstance(2019,02,28);    
            Date endate = Date.newInstance(2019,01,19);
        
          Mapping_Setting__c setting=new Mapping_Setting__c(name='FCST Mapping Data',
                                                              Cost_Center__c='fcst_cost_center__c',
                                                              FCST_ProgramManager__c = 'lastmodifiedbyid',
                                                              Fcst_CPM__c='fcst_cpm_region__c',
                                                              Fcst_EndDate__c='fcst_end_date__c',
                                                              Fcst_SalesRegion__c='fcst_account_region_vertical__c',
                                                              Fcst_StartDate__c='fcst_start_date__c',
                                                              Fcst_SubRegion__c='fcst_account_sub_region__c',
                                                              Fcst_Revenue_Type__c='fcst_revenue_type__c',
                                                              Geo__c='fcst_geo_codes__c',
                                                              Geo_Name__c='geo_name__c',
                                                              Fcst_Q__c='fcst_q__c	');
            insert setting;
            
        
                 String qnum = 'Q000-035';
                Account ac = new Account();
                ac.Name = 'Account';
                insert ac;
        
                Opportunity opt = new Opportunity();
                opt.Name = '1Oppy for Closed';
                opt.AccountId = ac.Id;
                opt.Fcst_Text_QNum__c = 'fcst_q__c';
                opt.StageName = 'Closed Won';
                opt.CloseDate = srtDate;
                insert opt;
        
        PageReference pgf = Page.FCST_Update_Contract;
            Test.setCurrentPage(pgf);
            
        pgf.getparameters().put('id',String.valueOf(opt.Id));
        
        List<Fcst_Cost_Center__c> costC = new List<Fcst_Cost_Center__c>();
        Fcst_Cost_Center__c costCentr = new Fcst_Cost_Center__c();
        costCentr.Name = '010A';
        costCentr.Cost_Center_Description__c = 'TestDataDESC';
        costCentr.BSLA__c = '203563';
        costCentr.BU_Level1__c = 'Corporate';
        costCentr.BU_Level_2__c = 'Corp';
        insert costCentr;
        costC.add(costCentr);
        
        Planning_Version__c plv = new Planning_Version__c();
        plv.Name = '2019-March';
        plv.Version_Status__c =  'Open (Admin)';
        insert plv;
        
        Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c();
            fyp.Name = '2019';
            fyp.StartDate__c = srtDate;
            fyp.EndDate__c = endate;
            insert fyp;
         
        List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
        for(Integer i=0;i<20;i++){
        Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
        fym.Short_Label__c = 'TestData';
        fym.Period_Number__c = 1;
        fym.Fiscal_Planning_Year__c = fyp.Id;
        fymList.add(fym);
        }
        
        if(fymList!=null && !fymList.isEmpty()){
            insert fymList;
        }
        
        Fiscal_Year_Model__c fym2 = new Fiscal_Year_Model__c();
        fym2.Short_Label__c = 'TestData2';
        fym2.Period_Number__c = 2;
        fym2.Fiscal_Planning_Year__c = fyp.Id;
        insert fym2;
        
       FCST_Contract__c contr = new FCST_Contract__c();
            contr.Fcst_Account__c = ac.Id;
            contr.Contract__c = 'TestContract';
            contr.Contract_Description__c = 'TestDescr';
           // contr.Contract_Owner__c = loginUser.id;
            contr.FCST_Contract_Created_Year__c = '2019';
            contr.Fcst_Geo_Name__c = 'geo name';
            contr.Fcst_Geo_Number__c = 99999;
            contr.FCST_Q__c = 'QData';
            contr.Opportunity__c = opt.Id;
            insert contr;
            
            Contract_LineItem__c contLineItem = new Contract_LineItem__c();
            contLineItem.FCST_Contract__c = contr.Id;
            contLineItem.FCST_Fiscal_Year_List__c = fyp.Id;
            contLineItem.Risk_Factor__c = 233;
            insert contLineItem;
        
        List<FCST_Initial_Forecast__c> intFcstList = new List<FCST_Initial_Forecast__c>();
        for(Integer i=0;i<20;i++){
        FCST_Initial_Forecast__c iniFcst = new FCST_Initial_Forecast__c();
        iniFcst.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
        iniFcst.FCST_Fiscal_Year_List__c = fymList[0].Fiscal_Planning_Year__c;
        iniFcst.Fcst_Amount__c = 0;
        iniFcst.Contract_LineItem__c = contLineItem.Id;
        iniFcst.FCST_Contract__c = contr.Id;
        iniFcst.Account__c = ac.Id;
        intFcstList.add(iniFcst);
        }
        if(intFcstList!=null && !intFcstList.isEmpty()){
            insert intFcstList;
        }
        
       // for(Fiscal_Year_Model__c fymm:fymList){
       /* FCST_Initial_Forecast__c iniFcst = new FCST_Initial_Forecast__c();
        iniFcst.FCST_Planning_Fiscal_Year__c = fymList[0].Id;
        iniFcst.FCST_Fiscal_Year_List__c = fyp.Id;
        iniFcst.Fcst_Amount__c = 0;
        iniFcst.Contract_LineItem__c = contLineItem.Id;
        iniFcst.FCST_Contract__c = contr.Id;
        iniFcst.Account__c = ac.Id;
        insert iniFcst;*/
        // }

        FCST_Opportunity_Initial_Forecast__c oif = new FCST_Opportunity_Initial_Forecast__c();
        oif.Fcst_Fiscal_Period__c = fymList[0].Id;
        oif.Fcst_Weighted_Revenue__c = 84;
        oif.Fcst_Opportunity__c = opt.Id;
        oif.FCST_Planning_Version__c = plv.Id;
        oif.Fcst_Q__c =  opt.Fcst_Text_QNum__c;
        insert oif;
        
        FCST_Opportunity_Initial_Forecast__c oif2 = new FCST_Opportunity_Initial_Forecast__c();
        oif2.Fcst_Fiscal_Period__c = fym2.Id;
        oif2.Fcst_Weighted_Revenue__c = 1000;
        oif2.Fcst_Opportunity__c = opt.Id;
        oif2.FCST_Planning_Version__c = plv.Id;
        oif2.Fcst_Q__c =  opt.Fcst_Text_QNum__c;
        insert oif2;
        
       /* Fcst_Geo_Code__c geoCode = new Fcst_Geo_Code__c();
        geoCode.Name = 'fcst_geo_code__c';
        insert geoCode;*/
        
        ApexPages.StandardController std=new ApexPages.StandardController(opt);
        FCST_UpdateContractExtension  updContract = new FCST_UpdateContractExtension(std);
        FCST_UpdateContractExtension.WMonths months = new FCST_UpdateContractExtension.WMonths(2000,'Test');
        List<FCST_UpdateContractExtension.ContractLinewrapper> contLineWrpList = new List<FCST_UpdateContractExtension.ContractLinewrapper>();
        //FCST_UpdateContractExtension.ContractLinewrapper contrLine = new FCST_UpdateContractExtension.ContractLinewrapper('Test',contLineItem,intFcstList,true);
       // contLineWrpList.add(contrLine);
        FCST_UpdateContractExtension.Contractwrapper contrWrp = new FCST_UpdateContractExtension.Contractwrapper(contr,intFcstList,contLineWrpList);
        
        FCST_UpdateContractExtension.getOpportunityStage(String.valueOf(opt.Id));
        updContract.cfiscalyear = '2019';
        updContract.generateDynamicId();
        updContract.lineItemDuplicateValue();
        //updContract.costcentremethod();
        updContract.createInitialForecast(contr.Id,contLineItem.Id,ac.Id);
        updContract.getProduct();
        updContract.searchContract();
        updContract.getCostCentre();
        updContract.getFiscalYears();
        updContract.searchContract();
        updContract.getCostCentre();
        updContract.getOpportunityInitialTotal();
        updContract.lineItemInitialTotal();
        updContract.getBSLA();
        updContract.addContractLineItem();
        updContract.removeContractLineItem();
        updContract.RevertProduct();
        updContract.EditProduct();
        updContract.goBack();
        updContract.saveContract();

        }
    }