Compucom CCQA Org 100919/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FCST_CPM_Region__c</fullName>
        <label>FCST CPM_Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US-DC Area</fullName>
                </value>
                <value>
                    <fullName>US-Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>US-Midwest</fullName>
                </value>
                <value>
                    <fullName>US-Ohio Valley</fullName>
                </value>
                <value>
                    <fullName>US-South Central</fullName>
                </value>
                <value>
                    <fullName>US-Southeast</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Target</fullName>
                </value>
                <value>
                    <fullName>US-US Bank</fullName>
                </value>
                <value>
                    <fullName>CAN-Canada</fullName>
                </value>
                <value>
                    <fullName>CAN-BMO</fullName>
                </value>
                <value>
                    <fullName>CAN-Gov&apos;t of Ontario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Actual_Model__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>Actual_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract_LineItem__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract LineItem</label>
        <referenceTo>Contract_LineItem__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>FCST Actual Model</label>
    <nameField>
        <displayFormat>Actual-{00000}</displayFormat>
        <label>Actual Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Actual Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Contract_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>Contract LineItems</relationshipLabel>
        <relationshipName>Contract_LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract LineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contract LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Owner(UNUSED)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Contract_Created_Year__c</fullName>
        <label>FCST Baseline Created Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FCST Contracts</relationshipLabel>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>FCST Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/FCST_Initial_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Initial Forecast</label>
    <nameField>
        <label>FCST Initial Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Initial Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/FCST_Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Account_CPM_Region__c</fullName>
        <label>Account CPM Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Product Model</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>FCST Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Product Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period_Id__c</fullName>
        <label>Fiscal Period Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Planning_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal_Planning_Year</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>FCST Planning Fiscal Years</relationshipLabel>
        <relationshipName>FCST_Planning_Fiscal_Years</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Long_Label__c</fullName>
        <label>Long_Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <label>Period Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Label__c</fullName>
        <label>Short Label</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Data_Entry_Closed_Date__c</fullName>
        <label>Data Entry Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Start_Date__c</fullName>
        <label>Data Entry Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_Label__c</fullName>
        <label>Long_Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthName__c</fullName>
        <label>MonthName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Current_Period__c</fullName>
        <label>Planning Version Current Period</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Label__c</fullName>
        <label>Short Label Unused Field</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/TEST_FCST_CompucomBaseLineWorkbench.cls
@isTest
public class TEST_FCST_CompucomBaseLineWorkbench {
    static testmethod void getData1(){
        user u=[select id,UserRoleId from user where id=:userinfo.getUserId()];
        list<FCST_Initial_Forecast__c> initial_flist = new list<FCST_Initial_Forecast__c>();
         FCST_UTIL.InsertTriggerMappingFields();
        system.runAs(u){
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            UserRole ur = new UserRole(Name = 'CEO',ParentRoleId = u.UserRoleId);
            insert ur;
            
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            
            User u1 = new User(Alias = 'standt', Email=uniqueName+'@testorg.com', 
                               EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = ur.id, 
                               TimeZoneSidKey='America/Los_Angeles', UserName=uniqueName+'@testorg.com');
            insert u1;
            Date fstartDate = Date.newInstance(2018,1,1);
            Date fendDate = Date.newInstance(2018,12,31);
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c(Name = '2018',StartDate__c = fstartDate,EndDate__c = fendDate);
            insert fyp;
            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            map<integer,Fiscal_Year_Model__c> fymmap = new map<integer,Fiscal_Year_Model__c>();
            for(Integer i=1;i<20;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = i<10?('FY2018P0'+string.valueOf(i)):('FY2018P'+string.valueOf(i));
                    fym.End_Date__c = fstartDate;
                fym.Start_Date__c = fendDate;
                fym.Fiscal_Planning_Year__c = fyp.Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = fstartDate;
                fymmap.put(i,fym);
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
            Date startDate = Date.newInstance(2018,1,1);
            Date endDate = startDate.addDays(30);
            Planning_Version__c plversionObj = new Planning_Version__c();
            plversionObj.Name='2018';
            plversionObj.Data_Entry_Start_Date__c=startDate;
            plversionObj.Data_Entry_Closed_Date__c=endDate;
            plversionObj.Fiscal_Year_Planning__c=fyp.Id;
            plversionObj.Planning_Version_Fiscal_Year__c='2018';
            plversionObj.Long_Label__c='January';
            plversionObj.Version_Status__c='Open (Admin)';
            plversionObj.Month_Number__c=1;
            plversionObj.MonthName__c='January';
            plversionObj.Period_Number__c=1;
            plversionObj.Planning_Version_Current_Period__c='1';
            plversionObj.SequenceNo__c=1;
            insert plversionObj;
            Account acc = new Account(Name='Test Account',fcst_cpm_region__c='US-DC Area');
            insert acc;
            FCST_Product_Model__c pm = new FCST_Product_Model__c(Account_CPM_Region__c='US-DC Area',Account__c=acc.Id);
            FCST_Contract__c contr = new FCST_Contract__c();
            // contr.name = 'Contract412368';
            contr.Fcst_Account__c = acc.Id;
            contr.Contract__c = 'Contract412368';
            contr.FCST_Contract_Created_Year__c = '2018';   
            contr.Contract_Owner__c= u.id;
            insert contr;
            Contract_LineItem__c fcl = new Contract_LineItem__c();
            //  fcl.name = 'sample test';
            fcl.FCST_Contract__c = contr.id;
            insert fcl;
            for(Integer i=1;i<20;i++){
                FCST_Initial_Forecast__c flist= new FCST_Initial_Forecast__c();
                //for(integer i=0;i<101;i++){
                flist.name='Contract412368';
                flist.Account__c =acc.id;
                flist.FCST_Contract__c = contr.id;
                flist.Contract_LineItem__c = fcl.id;
                flist.Planning_Version__c = plversionObj.Id;
                flist.FCST_Planning_Fiscal_Year__c=fymmap.get(i).id;
                flist.Fcst_Amount__c = 2000;
                
                initial_flist.add(flist);
            }
            insert initial_flist; 
            // }
            list<Actual_Model__c> amlist = new list<Actual_Model__c>();
            for(Integer i=1;i<20;i++){
                Actual_Model__c actModel = new Actual_Model__c();
                actModel.Account__c = acc.Id;
                actModel.FCST_Contract__c=contr.id;
                actModel.Actual_Type__c = 'Baseline';
                actModel.Contract_LineItem__c = fcl.Id;
                actModel.Actual_Amount__c = 20000;
                actModel.Fiscal_Period__c = fymmap.get(i).id;
                actModel.FCST_Planning_Version__c = plversionObj.Id;
                actModel.Fiscal_Year__c = fyp.Id;
                //  insert actModel;
                amlist.add(actModel);
            }
            insert amlist;
            test.startTest();
            Test.setCurrentPageReference(new PageReference('Page.FCST_CompucomBaseLineWorkbenchNewPage')); 
            System.currentPageReference().getParameters().put('pv', plversionObj.id);
            System.currentPageReference().getParameters().put('AccId', acc.id);
            System.currentPageReference().getParameters().put('su', u.id);
            System.currentPageReference().getParameters().put('getincreaseValue', '5');
            System.currentPageReference().getParameters().put('id', initial_flist[0].id);
            System.currentPageReference().getParameters().put('planningModelAmount', '10');
            FCST_CompucomBaseLineWorkbenchNewPage cc = new FCST_CompucomBaseLineWorkbenchNewPage();
            cc.total_size =10;
            cc.getPlanningYearOptionList();
            cc.getContractChange();
            cc.mainfetchOppRecord();
            cc.updatePlanningModel();
           // cc.updateRiskFector();
            cc.gotohomepage();
            cc.BackPage();
            cc.Beginning();
            cc.Previous();
            cc.Next();
            cc.End();
            cc.getDisablePrevious();
            cc.getDisableNext();
            cc.getTotal_size();
            cc.getPageNumber();
            cc.getTotalPages();
            
            test.stopTest();
        }
    }


   static testmethod void getData2(){
        FCST_UTIL.InsertTriggerMappingFields();
            user u=[select id,UserRoleId from user where id=:userinfo.getUserId()];
        list<FCST_Initial_Forecast__c> initial_flist = new list<FCST_Initial_Forecast__c>();
        system.runAs(u){
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            UserRole ur = new UserRole(Name = 'CEO',ParentRoleId = u.UserRoleId);
            insert ur;
            
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            
            User u1 = new User(Alias = 'standt', Email=uniqueName+'@testorg.com', 
                               EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US', ProfileId = p.Id,UserRoleId = ur.id, 
                               TimeZoneSidKey='America/Los_Angeles', UserName=uniqueName+'@testorg.com');
            insert u1;
            Date fstartDate = Date.newInstance(2018,1,1);
            Date fendDate = Date.newInstance(2018,12,31);
            Fiscal_Year_Planning__c fyp = new Fiscal_Year_Planning__c(Name = '2018',StartDate__c = fstartDate,EndDate__c = fendDate);
            insert fyp;
            List<Fiscal_Year_Model__c> fymList = new List<Fiscal_Year_Model__c>();
            map<integer,Fiscal_Year_Model__c> fymmap = new map<integer,Fiscal_Year_Model__c>();
            for(Integer i=1;i<20;i++){
                Fiscal_Year_Model__c fym = new Fiscal_Year_Model__c();
                fym.Name = i<10?('FY2018P0'+string.valueOf(i)):('FY2018P'+string.valueOf(i));
                fym.End_Date__c = fstartDate;
                fym.Start_Date__c = fendDate;
                fym.Fiscal_Planning_Year__c = fyp.Id;
                fym.Fiscal_Period_Id__c = '20';
                fym.Fiscal_Quarter__c = 'Q1';
                fym.Fiscal_Year__c = '2019';
                fym.Long_Label__c = 'February';
                fym.Period_Name__c = 'February';
                fym.Period_Number__c = 2;
                fym.Record_Source__c = 'Installation';
                fym.Short_Label__c = 'Feb';
                fym.Start_Date__c = fstartDate;
                fymmap.put(i,fym);
                fymList.add(fym);
            }
            if(fymList!=null && !fymList.isEmpty()){
                insert fymList;
            }
            Date startDate = Date.newInstance(2018,1,1);
            Date endDate = startDate.addDays(30);
            Planning_Version__c plversionObj = new Planning_Version__c();
            plversionObj.Name='2018';
            plversionObj.Data_Entry_Start_Date__c=startDate;
            plversionObj.Data_Entry_Closed_Date__c=endDate;
            plversionObj.Fiscal_Year_Planning__c=fyp.Id;
            plversionObj.Planning_Version_Fiscal_Year__c='2018';
            plversionObj.Long_Label__c='January';
            plversionObj.Version_Status__c='Open (Admin)';
            plversionObj.Month_Number__c=1;
            plversionObj.MonthName__c='January';
            plversionObj.Period_Number__c=1;
            plversionObj.Planning_Version_Current_Period__c='1';
            plversionObj.SequenceNo__c=1;
            insert plversionObj;
            Account acc = new Account(Name='Test Account');
            insert acc;
            FCST_Contract__c contr = new FCST_Contract__c();
            // contr.name = 'Contract412368';
            contr.Fcst_Account__c = acc.Id;
            contr.Contract__c = 'Contract412368';
            contr.FCST_Contract_Created_Year__c = '2018';   
            contr.Contract_Owner__c= u.id;
            contr.Fcst_Geo_Numbers__c = 'TestNum';
            insert contr;
            
            List<Contract_LineItem__c> cliList = new List<Contract_LineItem__c>();
            Contract_LineItem__c fcl = new Contract_LineItem__c();
            //  fcl.name = 'sample test';
            fcl.FCST_Contract__c = contr.id;
            fcl.BSLA_Number__c = '20';
            fcl.Cost_Center__c = 'Test CC';
            cliList.add(fcl);
            
            insert cliList;
            
            for(Integer i=1;i<20;i++){
                FCST_Initial_Forecast__c flist= new FCST_Initial_Forecast__c();
                //for(integer i=0;i<101;i++){
                flist.name='Contract412368';
                flist.Account__c =acc.id;
                flist.FCST_Contract__c = contr.id;
                flist.Contract_LineItem__c = fcl.id;
                flist.Planning_Version__c = plversionObj.Id;
                flist.FCST_Planning_Fiscal_Year__c=fymmap.get(i).id;
                flist.Fcst_Amount__c = 2000;
                
                initial_flist.add(flist);
            }
            insert initial_flist; 
            // }
            list<Actual_Model__c> amlist = new list<Actual_Model__c>();
            for(Integer i=1;i<20;i++){
                Actual_Model__c actModel = new Actual_Model__c();
                actModel.Account__c = acc.Id;
                actModel.FCST_Contract__c=contr.id;
                actModel.Actual_Type__c = 'Baseline';
                actModel.Contract_LineItem__c = fcl.Id;
                actModel.Actual_Amount__c = 20000;
                actModel.BSLA__c =  fcl.BSLA_Number__c;
                actModel.FCST_CC__c = fcl.Cost_Center__c;
                actModel.Fiscal_Year__c = fymList[0].Fiscal_Planning_Year__c;
                actModel.Fiscal_Period__c = fymmap.get(i).id;
                actModel.FCST_Planning_Version__c = plversionObj.Id;
                actModel.Fiscal_Year__c = fyp.Id;
                actModel.Contract_LineItem__c = cliList[0].Id;
                actModel.FCST_GEO__c = contr.Fcst_Geo_Numbers__c;
                //  insert actModel;
                amlist.add(actModel);
            }
            insert amlist;
            
            
             list<Actual_Model__c> amlist1 = new list<Actual_Model__c>();
            for(Integer i=1;i<20;i++){
                Actual_Model__c actModel1 = new Actual_Model__c();
                actModel1.Account__c = acc.Id;
                actModel1.FCST_Contract__c=contr.id;
                actModel1.Actual_Type__c = 'Baseline';
                actModel1.Contract_LineItem__c = fcl.Id;
                actModel1.Actual_Amount__c = 0;
                actModel1.BSLA__c =  fcl.BSLA_Number__c;
                actModel1.FCST_CC__c = fcl.Cost_Center__c;
                actModel1.Fiscal_Year__c = fymList[0].Fiscal_Planning_Year__c;
                actModel1.Fiscal_Period__c = fymmap.get(i).id;
                actModel1.FCST_Planning_Version__c = plversionObj.Id;
                actModel1.Fiscal_Year__c = fyp.Id;
                actModel1.Contract_LineItem__c = cliList[0].Id;
                actModel1.FCST_GEO__c = contr.Fcst_Geo_Numbers__c;
                //  insert actModel;
                amlist1.add(actModel1);
            }
            insert amlist1;
            
            
            test.startTest();
            Test.setCurrentPageReference(new PageReference('Page.FCST_CompucomBaseLineWorkbenchNewPage')); 
            System.currentPageReference().getParameters().put('pv', plversionObj.id);
            System.currentPageReference().getParameters().put('AccId', acc.id);
            System.currentPageReference().getParameters().put('su', u.id);
            System.currentPageReference().getParameters().put('getincreaseValue', '5');
            System.currentPageReference().getParameters().put('id', initial_flist[0].id);
            System.currentPageReference().getParameters().put('planningModelAmount', '10');
            System.currentPageReference().getParameters().put('lineItemId', fcl.Id);
            System.currentPageReference().getParameters().put('periodnumber', plversionObj.Id);
            System.currentPageReference().getParameters().put('actualAmount', '20000');
            
            FCST_CompucomBaseLineWorkbenchC cc = new FCST_CompucomBaseLineWorkbenchC();
            cc.strPlanningVersion = '2018';
            cc.strPlanningVersion = '2019';
            cc.total_size =10;
            cc.Beginning();
            //cc.Previous();
            cc.Next();
            cc.End();
            cc.getDisablePrevious();
            cc.getDisableNext();
            cc.getTotal_size();
            cc.getPageNumber();
            cc.getTotalPages();
            cc.getPlanningYearOptionList();
            cc.getContractChange();
            cc.mainfetchOppRecord();
            cc.fetchOppRecord();
            cc.updatePlanningModel();
            cc.updateRiskFactor();
            cc.gotohomepage();
            cc.updateActualModel();
            cc.BackPage();
}
}
}