Compucom CCQA Org 100919/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FCST_GeoCodes__c</fullName>
        <label>FCST GeoCodes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FCST_Program_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST_Program Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Actual_Model__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>Actual_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Amount__c</fullName>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_LineItem__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contract LineItem</label>
        <referenceTo>Contract_LineItem__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_GEO__c</fullName>
        <label>FCST GEO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Planning_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Year</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GEO_Description__c</fullName>
        <label>GEO Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GEO__c</fullName>
        <label>GEO_unused</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Actual Models</relationshipLabel>
        <relationshipName>FCST_Actual_Models_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Stream__c</fullName>
        <label>Revenue Stream</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FCST Actual Model</label>
    <nameField>
        <displayFormat>Actual-{00000}</displayFormat>
        <label>Actual Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Actual Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Contract_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Contract__c</fullName>
        <label>FCST Contract</label>
        <referenceTo>FCST_Contract__c</referenceTo>
        <relationshipLabel>Contract LineItems</relationshipLabel>
        <relationshipName>Contract_LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Description__c</fullName>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contract LineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contract LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/FCST_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Description__c</fullName>
        <label>Contract Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Contracts</relationshipLabel>
        <relationshipName>FCST_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Contract</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>FCST Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_GeoCodes__c</fullName>
        <label>FCST GeoCodes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FCST_ProgramManager__c</fullName>
        <label>FCST_ProgramManager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Program_Executive__c</fullName>
        <label>FCST_Program Executive</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_BusinessUnit__c</fullName>
        <label>Fcst_BusinessUnit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_CPM__c</fullName>
        <label>Fcst_CPM</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_SVC_YR1__c</fullName>
        <label>Opportunity SVC YR1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_TCV__c</fullName>
        <label>Opportunity TCV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_In_Months__c</fullName>
        <label>Term In Months</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transition_Date__c</fullName>
        <label>Transition Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipLabel>FCST Planning Versions</relationshipLabel>
        <relationshipName>FCST_Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Gap_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Gap Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Month_Number__c</fullName>
        <label># Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/classes/FCST_Actuals_DataExtract.cls
public class FCST_Actuals_DataExtract {

    public List<wrapperContractLineWise> wrapperContractLineWiseList{get; set;}    
    public string s_FilterPlanningYear{get;set;}
    public String selectedYr{get;set;}
    public String nextYear{get;set;}
    public String openAdminVersion{get;set;}
    
    public string cpmRegionLabelName;
    public string PMTypeLabelName;
    public string PETypeLabelName;
    public string GeoLabelName;
    
    public string serviceStartDateAPI;
    public string serviceEndDateAPI;
    public string transitionDateAPI;
    public string termsInMonthAPI;
    
    public string costCenterAPI;
    public string businessUnitAPI;
    
    public string TCVAPI;
    public string SVCYR1API;
    public string oppGeoLookupAPI;
    
    public string currentFullYear{get;set;}
    public string nextFullYear{get;set;}
    
    public date todayDate {get;set;}
    public String formattedDate {get;set;}
    public String errorMsg{get;set;}
    public List<SelectOption> FilterPlanningVersion{get;set;}
    
    
    
     public static String reduceName(String str){
      if(str!=null && str.length()>25){
        str=str.substring(0, 25)+'...';
      }
     
     return str;
    
    }
           //>>>>>>>>>>pagination start>>>>>>>>>>
        public integer counter=0; 
        public integer list_size=5;  
        public integer total_size;
        
        public PageReference Beginning() { 
          counter = 0;
         // System.debug('>>Beginning>>counter>>>'+counter);
         updateWrapperList();
          return null;
       }
    
       public PageReference Previous() { 
          counter -= list_size;
         // System.debug('>>Previous>>list_size>>>'+list_size);
        //  System.debug('>>Previous>>counter>>>'+counter);
         updateWrapperList();
          return null;
       }
    
       public PageReference Next() { 
          counter += list_size;
          
        //  System.debug('>>Next>>list_size>>>'+list_size);
      //    System.debug('>>Next>>counter>>>'+counter);
          updateWrapperList();
          return null;
       }
    
     
       public PageReference End() { 
          counter = total_size - math.mod(total_size, list_size);
          if(counter==total_size){
            counter=counter-list_size;
          }
         // System.debug('>>End>>list_size>>>'+list_size);
         // System.debug('>>End>>counter>>>'+counter);
          updateWrapperList();
          return null;
       }
    
       public Boolean getDisablePrevious() { 
         if (counter>0) {
          return false;
          } else return true;
       }
    
       public Boolean getDisableNext() {
        if (counter + list_size < total_size){ 
            
            return false;} else return true;
        }
    
       public Integer getTotal_size() {
          return total_size;
       }
    
       public Integer getPageNumber() {
          return counter/list_size + 1;
       }
    
       public Integer getTotalPages() {
            if(total_size==null)
                total_size=0;
            
            if (math.mod(total_size, list_size) > 0) {
             return total_size/list_size + 1;
            } else {
             return (total_size/list_size);
         }
       }
     //>>>>>>>>>>pagination start End>>>>>>>>>>
     
     
    public FCST_Actuals_DataExtract(){
        
        Mapping_Setting__c mapCustomObj=Mapping_Setting__c.getValues('FCST Mapping Data');
        cpmRegionLabelName = mapCustomObj.Fcst_CPM__c;
        PMTypeLabelName=mapCustomObj.FCST_ProgramManager__c;
        PETypeLabelName=mapCustomObj.FCST_Program_Executive__c;
        GeoLabelName=mapCustomObj.FCST_GeoCodes__c;
        
         serviceStartDateAPI=mapCustomObj.Fcst_StartDate__c;
         serviceEndDateAPI=mapCustomObj.Fcst_EndDate__c;
         transitionDateAPI=mapCustomObj.Transition_Date__c;
         termsInMonthAPI=mapCustomObj.Term_In_Months__c;
        
        costCenterAPI=mapCustomObj.Cost_Center__c;
        businessUnitAPI=mapCustomObj.Fcst_BusinessUnit__c;
        
        TCVAPI=mapCustomObj.Opportunity_TCV__c;
        SVCYR1API=mapCustomObj.Opportunity_SVC_YR1__c;
        oppGeoLookupAPI=mapCustomObj.Geo__c;
        
        todayDate=date.today();
       
        String accQuery='select Id from Account where   '+cpmRegionLabelName+'!=null LIMIT 500';
         List<Account> accListVal=database.query(accQuery);
        System.debug('accListVal'+accListVal);
     //total_size=accListVal.size();
     // total_size=2;
            //System.debug('...total_size.....'+total_size);
         //formattedDate =todayDate.year()+'-'+todayDate.month()+'-'+todayDate.day();
         formattedDate =todayDate.month()+'/'+todayDate.day()+'/'+todayDate.year();
        getFilterPlanningYear();
        planningVersion();
        selectedYr=s_FilterPlanningYear.right(2);
        nextYear=String.ValueOf(Integer.ValueOf(selectedYr)+1);
        
        currentFullYear=s_FilterPlanningYear;
        nextFullYear=String.ValueOf(Integer.ValueOf(currentFullYear)+1);
        
        
        
        set<string> setValidVersions = new set<string>{'Open (Admin)'};
        List<Planning_Version__c> pvlist=[select Id,Name,Planning_Version_Fiscal_Year__c from Planning_Version__c where Version_Status__c IN: setValidVersions and Is_this_a_Budget_Planning_Version__c = false and Is_this_a_Gap_Planning_Version__c = false order by Planning_Version_Fiscal_Year__c];
        if(pvlist!=null && pvlist.size()>0)
            openAdminVersion=pvlist[0].Name;
            
            
      updateWrapperList();
        
    }
    
    public List<SelectOption> getFilterPlanningYear() {
      
    List<SelectOption> options = new List<SelectOption>();
    String CurrentYear = String.ValueOf(Date.today().year());
        Set<String> yrList = new Set<String>();
        set<string> setValidVersions = new set<string>{'Closed','Open (Admin)'};
        List<Planning_Version__c> pvlist=[select Id,Name,Version_Status__c,Planning_Version_Fiscal_Year__c,Fiscal_Year_Planning__r.Name from Planning_Version__c where   Version_Status__c IN: setValidVersions and Is_this_a_Budget_Planning_Version__c = false and Is_this_a_Gap_Planning_Version__c = false order by Planning_Version_Fiscal_Year__c];
        if(pvlist!=null && pvlist.size()>0){ 
            for(Planning_Version__c pvObj:pvlist){
                yrList.add(pvObj.Fiscal_Year_Planning__r.Name);
                if(pvObj.Fiscal_Year_Planning__r.Name==CurrentYear)
                    s_filterPlanningYear=pvObj.Fiscal_Year_Planning__r.Name;
            }
        }
        
        
        
        for(String str:yrList){
            options.add(new SelectOption(str,str));
        }
        
       
        System.debug('options'+options);            
        return options;
    }
        
    public void onChangeYear() {
        planningVersion();
       // updateWrapperList();     
    }
    
    public void loadLandingUI() {
        counter = 0;
        updateWrapperList();
     
    }
    
 public List<SelectOption> planningVersion() {
         FilterPlanningVersion = new List<SelectOption>();
        set<string> setValidVersions = new set<string>{'Closed','Open (Admin)'};
        List<Planning_Version__c> pvlist=[select Id,Name,Version_Status__c,Planning_Version_Fiscal_Year__c from Planning_Version__c where Fiscal_Year_Planning__r.Name =:s_filterPlanningYear and  Version_Status__c IN: setValidVersions and Is_this_a_Budget_Planning_Version__c = false and Is_this_a_Gap_Planning_Version__c = false order by Planning_Version_Fiscal_Year__c];
        if(pvlist!=null && pvlist.size()>0){
            for(Planning_Version__c pvObj:pvlist){
                FilterPlanningVersion.add(new SelectOption(pvObj.Name,pvObj.Name));
                openAdminVersion=pvObj.Name;
            }
        }
        //System.debug('>>>options>>>'+options);
        return FilterPlanningVersion;
    }   
  
    
    public void updateWrapperList(){
        
        try{
            wrapperContractLineWiseList = new List<wrapperContractLineWise>();
            selectedYr=s_FilterPlanningYear.right(2);
            nextYear=String.ValueOf(Integer.ValueOf(selectedYr)+1);
        
           currentFullYear=s_FilterPlanningYear;
           nextFullYear=String.ValueOf(Integer.ValueOf(currentFullYear)+1);
            
            Integer currentYear=date.today().Year();
            String LineitemQuery = 'SELECT Id, name from Contract_LineItem__c where Id In(Select Contract_LineItem__c from  Actual_Model__c)';
            List<Contract_LineItem__c> conListVal = database.query(LineitemQuery);
            String ActualQuery ='SELECT Account__r.Name, Contract_LineItem__r.Fcst_Revenue_Type__c, Contract_LineItem__r.Cost_Center__c, GEO_Description__c,FCST_GEO__c,FCST_Contract__r.Contract__c,Contract_LineItem__c, Revenue_Stream__c,    FCST_Contract__r.Contract_Description__c,FCST_Contract__r.Name,FCST_Contract__r.Opportunity__c, LastModifiedBy.Name,LastModifiedDate, Contract_LineItem__r.Name, Contract_LineItem__r.Line_Description__c,Fiscal_Period__r.Fiscal_Year__c,Fiscal_Period__r.Month_Number__c, FCST_Planning_Version__r.Name,Actual_Amount__c from Actual_Model__c Where ';
             ActualQuery += ' FCST_Planning_Version__r.Name =: openAdminVersion  and Contract_LineItem__c IN:conListVal and Account__r.'+cpmRegionLabelName+' !=null  and Fiscal_Period__r.Fiscal_Year__c =:currentFullYear';
             ActualQuery += ' order by Account__r.Name,Contract_LineItem__r.Fcst_Revenue_Type__c';
            
             List<Actual_Model__c> ActualModelList = database.query(ActualQuery); 
            System.debug('ActualModelList'+ActualModelList);
            Map<Id,List<Actual_Model__c>> mapContractLineItemIdVsActualModelList = new Map<Id,List<Actual_Model__c>>();
            
            for(Actual_Model__c accModel : ActualModelList){
                    if(mapContractLineItemIdVsActualModelList.containsKey(accModel.Contract_LineItem__c)){
                        List<Actual_Model__c> existingModel=mapContractLineItemIdVsActualModelList.get(accModel.Contract_LineItem__c);
                        existingModel.add(accModel);
                        mapContractLineItemIdVsActualModelList.put(accModel.Contract_LineItem__c,existingModel);
                    }
                    else{
                        List<Actual_Model__c> newModelList = new List<Actual_Model__c>();
                        newModelList.add(accModel);
                        mapContractLineItemIdVsActualModelList.put(accModel.Contract_LineItem__c,newModelList);
                    }
            }
         
          //  datetime = createdDate;
           for(Id lineIdobj:mapContractLineItemIdVsActualModelList.keySet()){
             	System.debug('In lineIdobj>>'+lineIdobj);
                  List<double> ActualAmountList = new List<double>();
                    double Actual1=0,Actual2=0,Actual3=0,Actual4=0,Actual5=0,Actual6=0,Actual7=0,Actual8=0,Actual9=0,Actual10=0,Actual11=0,Actual12=0;
                    String contractLineItemName='',AccountName='',RevenueType='',CostCentre='',Geo='',Contractnum='',ContractLineDesc='',LastModifiedBy='',planningversion='',dataextdate='',lastdate='';
               		String contractLineItemName25Digit='',AccountName25Digit='',RevenueType25Digit='',Geo25Digit='',Contractnum25Digit='',ContractLineDesc25Digit='';
 					datetime modDate;
               Integer i=0;
               
                for(Actual_Model__c accModel:mapContractLineItemIdVsActualModelList.get(lineIdobj)){
                    i++;
                    System.debug('i'+i);
                     if(i==1){
                       modDate=accModel.LastModifiedDate;
                       LastModifiedBy=accModel.LastModifiedBy.Name; 
                                 }
                    if(accModel.LastModifiedDate!=null && (modDate<accModel.LastModifiedDate)){
                        modDate=accModel.LastModifiedDate;
                        LastModifiedBy=accModel.LastModifiedBy.Name;
                    }
                    if(modDate!=null){
                       lastdate = modDate.month()+'/'+modDate.day()+'/'+modDate.year();
                    }
                    if(accModel.Contract_LineItem__r.Name!=null){
                        contractLineItemName = accModel.Contract_LineItem__r.Name;
                    	contractLineItemName25Digit = reduceName(contractLineItemName);
                    }
                    if(accModel.Account__r.Name!=null){
               			AccountName = accModel.Account__r.Name;
                        AccountName25Digit = reduceName(AccountName);
                    }
                    if(accModel.Contract_LineItem__r.Fcst_Revenue_Type__c!=null){
                        RevenueType= accModel.Contract_LineItem__r.Fcst_Revenue_Type__c;
                        RevenueType25Digit =  reduceName(RevenueType);
                    }
                    if(accModel.Contract_LineItem__r.Cost_Center__c!=null)
                        CostCentre= accModel.Contract_LineItem__r.Cost_Center__c;
                    if(accModel.GEO_Description__c!=null && accModel.FCST_GEO__c!=null){
                        Geo= accModel.FCST_GEO__c+' '+accModel.GEO_Description__c;
                        Geo25Digit = reduceName(Geo);
                    }
                    if(accModel.FCST_Contract__r.Contract__c!=null){
                        Contractnum=accModel.FCST_Contract__r.Contract__c;
                        Contractnum25Digit =  reduceName(Contractnum);
                    }
                    if(accModel.Contract_LineItem__r.Line_Description__c!=null){
                        ContractLineDesc=accModel.Contract_LineItem__r.Line_Description__c;
                        ContractLineDesc25Digit =  reduceName(ContractLineDesc);
                    }
                      //  if(accModel.LastModifiedBy.Name!=null)
                       // LastModifiedBy=accModel.LastModifiedBy.Name;
                        if(accModel.FCST_Planning_Version__r.Name!=null)
                        planningversion=accModel.FCST_Planning_Version__r.Name;
                    	if(formattedDate!=null)
                            System.debug('formattedDate'+formattedDate);
                    	dataextdate = formattedDate;
                    	//if(accModel.LastModifiedDate!=null)
                            //lastdate=accModel.LastModifiedDate.month()+'/'+accModel.LastModifiedDate.day()+'/'+accModel.LastModifiedDate.year();
                        if(accModel.Fiscal_Period__r.Month_Number__c==1 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual1+= accModel.Actual_Amount__c;
                            System.debug('Amount1'+accModel.Actual_Amount__c);
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==2 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual2+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==3 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual3+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==4 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual4+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==5 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual5+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==6 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual6+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==7 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual7+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==8 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual8+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==9 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual9+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==10 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual10+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==11 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual11+= accModel.Actual_Amount__c;
                        }
                        if(accModel.Fiscal_Period__r.Month_Number__c==12 && accModel.Fiscal_Period__r.Fiscal_Year__c==currentFullYear){
                            Actual12+= accModel.Actual_Amount__c;
                        }
                    
                    
                }
                        ActualAmountList.add(Actual1);
                        ActualAmountList.add(Actual2);
                        ActualAmountList.add(Actual3);
                        ActualAmountList.add(Actual4);
                        ActualAmountList.add(Actual5);
                        ActualAmountList.add(Actual6);
                        ActualAmountList.add(Actual7);
                        ActualAmountList.add(Actual8);
                        ActualAmountList.add(Actual9);
                        ActualAmountList.add(Actual10);
                        ActualAmountList.add(Actual11);
                        ActualAmountList.add(Actual12);
                        System.debug('ActualAmountList'+ActualAmountList);
                wrapperContractLineWise wrapList = new	wrapperContractLineWise(contractLineItemName,contractLineItemName25Digit,AccountName,AccountName25Digit,RevenueType,RevenueType25Digit,CostCentre,Geo,Geo25Digit,Contractnum,Contractnum25Digit,ContractLineDesc,ContractLineDesc25Digit,LastModifiedBy,planningversion,lastdate,dataextdate,ActualAmountList);
                System.debug('wrapList'+wrapList);
                if(wrapList!=null){wrapperContractLineWiseList.add(wrapList);}
            }
            
        }
        catch(Exception e) {
            ApexPages.Message apexMessage1 = new ApexPages.Message(ApexPages.Severity.Error, 'Error message :-'+ e.getMessage());
            ApexPages.Message apexMessage2 = new ApexPages.Message(ApexPages.Severity.Error, 'Error Line Number :-'+ e.getLineNumber());
            ApexPages.addMessage(apexMessage1); 
            ApexPages.addMessage(apexMessage2); 
            
                System.debug('The following exception has occurred: ' + e.getMessage());
                System.debug('Line number: ' + e.getLineNumber()); 
            }
        
        
    }
    

    
    public pagereference gotohomepage(){
        PageReference pg = new Pagereference('/home/home.jsp');
        pg.setredirect(true);
        return pg;
    }
    
    public void callBatchClass(){
        FCST_ActualData_Extract_Batch_Download uca = new FCST_ActualData_Extract_Batch_Download(s_FilterPlanningYear,openAdminVersion);
        Database.executeBatch(uca,5);
    }
    
    
    
        
    public class wrapperContractLineWise{
        public String contractLineItemName{get;set;}
        public String AccountName{get;set;}
        public String RevenueType{get;set;}
        public String Geo{get;set;}   
        public String Contractnum{get;set;}
        public String ContractLineDesc{get;set;}
        public String contractLineItemName25Digit{get;set;}
        public String AccountName25Digit{get;set;}
        public String RevenueType25Digit{get;set;}
        public String CostCentre{get;set;}
        public String Geo25Digit{get;set;}   
        public String Contractnum25Digit{get;set;}
        public String ContractLineDesc25Digit{get;set;}
        public String LastModifiedBy{get;set;}
        public String planningversion{get;set;}
        public string lastdate{get;set;}
        public string dataextdate{get;set;}
        public List<double> doubleAmount{get;set;}
     
        public wrapperContractLineWise(String contractLineItemName,String contractLineItemName25Digit,String AccountName,String AccountName25Digit,String RevenueType,String RevenueType25Digit,String CostCentre,String Geo,String Geo25Digit,String Contractnum,String Contractnum25Digit,String ContractLine,String ContractLineDesc25Digit,String LastModifiedBy,String planningversion,String lastdate,string dataextdate,List<double> doubleAmount)
        {	
            this.contractLineItemName=contractLineItemName;
            this.AccountName=AccountName;
            this.RevenueType=RevenueType;
            this.Geo=Geo;
            this.Contractnum=Contractnum;
            this.ContractLineDesc=ContractLineDesc;
            this.contractLineItemName25Digit=contractLineItemName25Digit;
            this.AccountName25Digit=AccountName25Digit;
            this.RevenueType25Digit=RevenueType25Digit;
            this.CostCentre=CostCentre;
            this.Geo25Digit=Geo25Digit;
            this.Contractnum25Digit=Contractnum25Digit;
            this.ContractLineDesc25Digit=ContractLineDesc25Digit;
            this.LastModifiedBy=LastModifiedBy;
            this.planningversion=planningversion;
            this.lastdate = lastdate;
            this.dataextdate = dataextdate;
      		this.doubleAmount=doubleAmount;
        }
    }
    
    

     
}