Compucom CCQA Org 100919/src/objects/FCST_Opportunity_Initial_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Opportunity Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Opportunity_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCST_Product_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FCST Product Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FCST_Revenue_Type__c</fullName>
        <formula>&apos;Consolidated Revenue&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FCST Revenue Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCST_Service_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FCST Service Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FCST_Transition_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>FCST Transition Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fcst_Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Fiscal Year</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipName>FCST_Oppy_Inicial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Opportunity Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Oppy_Initial_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Weighted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fcst Weighted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User_Adjusted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Adjusted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>FCST Opportunity Initial Forecast</label>
    <nameField>
        <label>FCST Oppy Initial Forecast  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Opportunity Initial Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/FCST_Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Adjusted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Adjusted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>FCST Product Model</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>FCST Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Product Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Fcst_Rev_Rec_Revenue_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Fcst_12_Month_Duration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fcst 12 Month Duration</label>
        <type>Checkbox</type>
    </fields>
    <label>Fcst Rev Rec Revenue Type</label>
</CustomObject>

Compucom CCQA/src/objects/FCST_Revenue_Recognization_Product__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <formula>Revenue_Type__c+&apos;#&apos;+Product__c+&apos;#&apos;+ Period__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offering Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>FCST Revenue Recognization Products</relationshipLabel>
        <relationshipName>FCST_Revenue_Recognization_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FCST Revenue Recognization Product</label>
    <nameField>
        <displayFormat>RRP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Revenue Recognization Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FCST_TR_YR1_Amount__c</fullName>
        <label>FCST_TR_YR1_Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_EndDate__c</fullName>
        <label>Fcst_EndDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Revenue_Type__c</fullName>
        <label>Fcst Revenue Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_StartDate__c</fullName>
        <label>Fcst_StartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_SVC_YR1__c</fullName>
        <label>Opportunity SVC YR1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_TCV__c</fullName>
        <label>Opportunity TCV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_In_Months__c</fullName>
        <label>Term In Months</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Data_Entry_Closed_Date__c</fullName>
        <label>Data Entry Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Start_Date__c</fullName>
        <label>Data Entry Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Gap_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Gap Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Planning Versions</relationshipLabel>
        <relationshipName>FCST_Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>FCST_Revenue_Type__c</fullName>
        <label>FCST Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Prod - Commodity</fullName>
                </value>
                <value>
                    <fullName>Prod - Enterprise</fullName>
                </value>
                <value>
                    <fullName>eXcell</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCST_PM_Forecast_Util.cls
/****
  Developer Name/Author:  Pritam Gupta
  Created Date: 9-Sep-2019
  Work item number from JIRA:-CRN-173
  Description: we are creating PM forecast and deleting Product model using Opporunity trigger and util class is-FCST_PM_Forecast_Util.

****/

public with sharing class FCST_PM_Forecast_Util {
    
    public FCST_PM_Forecast_Util(){
        
      }
    
    public Static Integer getDateId(Date dd){
        
        if(dd <> null){
            string cPeriod = (dd.Month()<10)? '0'+dd.Month():dd.Month()+'';
            string cDay = (dd.Day()<10)? '0'+dd.Day():dd.Day()+'';
            return Integer.ValueOf(dd.Year()+''+cPeriod+''+cDay);
        }
        return null;
    }
    
    public Static string get15DigitId(String mId){
        if(mId <> null && mId.trim() <> ''){
            return mId.substring(0,15);
        }
        return '';
    }
    
    public static void createPMForecast(list<Opportunity> oppList){
        try{
       
	        List<FCST_Product_Model__c> productmodelList =[Select Id from FCST_Product_Model__c where Opportunity__c IN :oppList];
	        List<Planning_Version__c> lstMPlanningversion =new List<Planning_Version__c>();
	                
	        if(Schema.sObjectType.Planning_Version__c.fields.Id.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Name.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Previous_Version__c.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Version_Status__c.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Data_Entry_Closed_Date__c.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Data_Entry_Start_Date__c.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Is_this_a_Budget_Planning_Version__c.isAccessible() && Schema.sObjectType.Planning_Version__c.fields.Is_this_a_Gap_Planning_Version__c.isAccessible()  ){
	            lstMPlanningversion = [select Id,Name,Previous_Version__c,Version_Status__c,Data_Entry_Closed_Date__c,Data_Entry_Start_Date__c from Planning_Version__c where Data_Entry_Start_Date__c <> null
	                                                         and Is_this_a_Budget_Planning_Version__c = false 
	                                                         and Is_this_a_Gap_Planning_Version__c = false
	                                                         and (Version_Status__c = 'Open (Admin)')
	                                                        ];
	        
	         }
	         
	         set<string> setRevenueType= new set<string>();
	         if(Schema.sObjectType.Fcst_Rev_Rec_Revenue_Type__c.fields.Id.isAccessible() && Schema.sObjectType.Fcst_Rev_Rec_Revenue_Type__c.fields.Name.isAccessible() && Schema.sObjectType.Fcst_Rev_Rec_Revenue_Type__c.fields.Fcst_12_Month_Duration__c.isAccessible()){
	            for(Fcst_Rev_Rec_Revenue_Type__c p: [select Id,Name from Fcst_Rev_Rec_Revenue_Type__c where Fcst_12_Month_Duration__c = true]){
	                setRevenueType.add(p.Name);
	            }
	         }
	         
	          map<Integer,Fiscal_Year_Model__c> mapFiscalYear = new map<Integer,Fiscal_Year_Model__c>();
	         map<String,Integer> mapFiscalId = new map<String,Integer>();
	         
	         map<String,Fiscal_Year_Model__c> mapPeriodNameVsPeriodObj = new map<String,Fiscal_Year_Model__c>();
	         
	         if(Schema.sObjectType.Fiscal_Year_Model__c.fields.Id.isAccessible() && Schema.sObjectType.Fiscal_Year_Model__c.fields.Name.isAccessible() && Schema.sObjectType.Fiscal_Year_Model__c.fields.Fiscal_Year__c.isAccessible() && Schema.sObjectType.Fiscal_Year_Model__c.fields.Start_Date__c.isAccessible() && Schema.sObjectType.Fiscal_Year_Model__c.fields.End_Date__c.isAccessible() && Schema.sObjectType.Fiscal_Year_Model__c.fields.Period_Number__c.isAccessible() ){
	            for(Fiscal_Year_Model__c fy : [select Id,Name,Fiscal_Year__c,Start_Date__c,End_Date__c,Period_Number__c from Fiscal_Year_Model__c where name <> null]){
	                if(fy.Name <> null && fy.Period_Number__c <> null && fy.Fiscal_Year__c <> null ){
	                    string cPeriod = (fy.Period_Number__c < 10)? '0'+fy.Period_Number__c:fy.Period_Number__c+'';
	                    mapFiscalYear.put(Integer.valueOf(fy.Fiscal_Year__c+''+cPeriod),fy);
	                    mapFiscalId.put(getDateId(fy.Start_Date__c)+'-'+getDateId(fy.End_Date__c),Integer.valueOf(fy.Fiscal_Year__c+''+cPeriod));
	                    
	                    mapPeriodNameVsPeriodObj.put(fy.Name,fy);
	                }
	            }
	        
	        }
	        
	           
	        
	        map<string,decimal> mapCMPercentage = new map<string,decimal>();
	        map<string,Integer> mapRegimeCount = new map<string,Integer>();
	        
	        if(Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Id.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Name.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Key__c.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Revenue_Type__c.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Product__c.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.product_code__c.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Period__c.isAccessible() && Schema.sObjectType.FCST_Revenue_Recognization_Product__c.fields.Amount__c.isAccessible()){
	            for(FCST_Revenue_Recognization_Product__c r : [select Id,Name,Key__c,Revenue_Type__c,Product__c,product_code__c,Period__c,Amount__c from FCST_Revenue_Recognization_Product__c where id <> null order by Period__c desc ]){
	                string key = r.Revenue_Type__c+'#'+get15DigitId(r.Product__c);
	                if(mapRegimeCount.containsKey(key)){
	                    mapRegimeCount.put(key,mapRegimeCount.get(key)+1);
	                }
	                else mapRegimeCount.put(key,1);
	                mapCMPercentage.put(r.key__c,r.Amount__c);        
	                
	                
	                         
	            }
	        }
	         
	         String oppTrYR1AmountAPI,oppSVCFullTCVAmountAPI,oppSVCYR1AmountAPI,oppTermMonthAPI,oppStartDateAPI,oppEndDateAPI,oppQhashAPI,productRevenueTypeAPI;
	         Mapping_Setting__c mapCustomObj=Mapping_Setting__c.getValues('FCST Mapping Data');
	        
	        if(mapCustomObj.FCST_TR_YR1_Amount__c!=null)
	            oppTrYR1AmountAPI=mapCustomObj.FCST_TR_YR1_Amount__c;
	            
	        if(mapCustomObj.Opportunity_SVC_YR1__c!=null)
	            oppSVCYR1AmountAPI=mapCustomObj.Opportunity_SVC_YR1__c;
	        
	        if(mapCustomObj.Opportunity_TCV__c!=null)
	            oppSVCFullTCVAmountAPI=mapCustomObj.Opportunity_TCV__c;
	            
	        if(mapCustomObj.Term_In_Months__c!=null)
	            oppTermMonthAPI=mapCustomObj.Term_In_Months__c;
	        
	        if(mapCustomObj.Fcst_StartDate__c!=null)
	            oppStartDateAPI=mapCustomObj.Fcst_StartDate__c;
	         
	        if(mapCustomObj.Fcst_EndDate__c!=null)
	            oppEndDateAPI=mapCustomObj.Fcst_EndDate__c;
	        
	        if(mapCustomObj.Fcst_Q__c!=null)
	            oppQhashAPI=mapCustomObj.Fcst_Q__c;
	        
	        if(mapCustomObj.Fcst_Revenue_Type__c!=null)
	            productRevenueTypeAPI=mapCustomObj.Fcst_Revenue_Type__c;    
	        
	        
	        
	        
	        String OppQuery='Select Id,'+oppTrYR1AmountAPI+','+oppSVCFullTCVAmountAPI+','+oppSVCYR1AmountAPI+','+oppTermMonthAPI+','+oppStartDateAPI+','+oppEndDateAPI+','+oppQhashAPI+',(select Id,TotalPrice ,opportunityId,Product2Id,Product2.'+productRevenueTypeAPI+' from OpportunitylineItems) from Opportunity where Id In:oppList';
	        List<Opportunity> oppListwithLineItem=database.query(OppQuery);
	        
	        If(oppListwithLineItem!=null && oppListwithLineItem.size()>0){
	            for(Opportunity oppObj:oppListwithLineItem){
	                
	                Decimal oppTrYR1Amount=0,oppSVCFullTCVAmount=0,oppSVCYR1Amount=0,oppTermMonth=0,trAmount=0,firstYr1SrAmount=0,modelservice12Month=0,modelserviceMore12Month=0,SrAFYR1Amount=0;
	                String oppQhash='';
	                date  oppStartDate,oppEndDate;
	                
	                Integer monthCount=0;
	                
	                if((Decimal) oppObj.get(oppTrYR1AmountAPI)!=null) 
	                    oppTrYR1Amount=(Decimal) oppObj.get(oppTrYR1AmountAPI);
	                if((Decimal) oppObj.get(oppSVCFullTCVAmountAPI)!=null) 
	                    oppSVCFullTCVAmount=(Decimal) oppObj.get(oppSVCFullTCVAmountAPI);
	                if((Decimal) oppObj.get(oppSVCYR1AmountAPI)!=null) 
	                    oppSVCYR1Amount=(Decimal) oppObj.get(oppSVCYR1AmountAPI);
	                
	                if((Date) oppObj.get(oppStartDateAPI)!=null) 
	                    oppStartDate=(Date) oppObj.get(oppStartDateAPI);
	                if((Date) oppObj.get(oppEndDateAPI)!=null) 
	                    oppEndDate=(Date) oppObj.get(oppEndDateAPI);
	                
	                if((Decimal) oppObj.get(oppTermMonthAPI)!=null) 
	                    oppTermMonth=(Decimal) oppObj.get(oppTermMonthAPI);
	                
	                if((String) oppObj.get(oppQhashAPI)!=null) 
	                    oppQhash=(String) oppObj.get(oppQhashAPI);    
	        
	                 monthCount = oppStartDate.monthsBetween(oppEndDate);
	                 monthCount++;
	                
	                if(monthCount!=null && monthCount!=0)
	                trAmount=oppTrYR1Amount/monthCount;
	                
	                
	                firstYr1SrAmount=oppSVCYR1Amount-oppTrYR1Amount;
	                
	                SrAFYR1Amount=oppSVCFullTCVAmount-oppSVCYR1Amount;
	                
	                if(monthCount<13){
	                	modelservice12Month=firstYr1SrAmount/monthCount;
	                }
	                if(monthCount>12 && (monthCount-12)!=0){
	                	modelserviceMore12Month=SrAFYR1Amount/(monthCount-12);
	                	modelservice12Month=firstYr1SrAmount/12;
	                }
	                
	                
	                
	                List<FCST_Opportunity_Initial_Forecast__c> newPMForecastModelList = new List<FCST_Opportunity_Initial_Forecast__c>();
	                Map<String,FCST_Opportunity_Initial_Forecast__c> mapPeriodNameVsMOdel= new  Map<String,FCST_Opportunity_Initial_Forecast__c>();
	                Integer year=0,month=0;
	                
	                year=oppStartDate.year();
	                month=oppStartDate.month();
	                
	                decimal serviceAmount=0;
	                serviceAmount=modelservice12Month;
	                Integer modelCount=1;
	                if(lstMPlanningversion!=null && lstMPlanningversion.size()>0){
		                for(Integer i=0;i<monthCount;i++){
		                	if(modelCount==13)
		                		serviceAmount= modelserviceMore12Month;
		                		
		                	String monthStr='';
		                	if(month==13){
		                		year++;
		                		month=1;
		                	}
		                	if(month<10){
		                		monthStr='0'+month;
		                	}
		                	else{
		                		monthStr=String.valueOf(month);
		                	}
		                	
		                	String periodName='FY'+year+'P'+monthStr;
		                	
				
		                	FCST_Opportunity_Initial_Forecast__c pmForecastObj = new FCST_Opportunity_Initial_Forecast__c();
		                	pmForecastObj.FCST_Planning_Version__c =lstMPlanningversion[0].Id;
		                	if(mapPeriodNameVsPeriodObj.containsKey(periodName)){
		                		pmForecastObj.Fcst_Fiscal_Period__c=mapPeriodNameVsPeriodObj.get(periodName).Id;
		                	}
		                	pmForecastObj.Fcst_Opportunity__c=oppObj.Id;
		                	if(oppQhash!=null){
		                		pmForecastObj.Fcst_Q__c=oppQhash;
		                	}	
		                	pmForecastObj.FCST_Transition_Revenue__c=trAmount;
		                	pmForecastObj.FCST_Service_Revenue__c=serviceAmount;
		                	
		                	
		                	newPMForecastModelList.add(pmForecastObj);
		                	mapPeriodNameVsMOdel.put(periodName,pmForecastObj);
		                	month++;
		                	modelCount++;
		                }
	                }
	                
	                for(OpportunitylineItem lineObj:oppObj.OpportunitylineItems){
	                    String revenueType='';
	                    
	                    Integer yearPro=0,monthPro=0,productNumber=1;
	                    yearPro=oppStartDate.year();
	                	monthPro=oppStartDate.month();
	                    Decimal totalLineItemAmount=0;
	                    
	                    if(lineObj.TotalPrice!=null)
	                    totalLineItemAmount=lineObj.TotalPrice;
	                    
	                    
	                    if(lineObj.getSObject('Product2')!=null && (String)lineObj.getSObject('Product2').get(productRevenueTypeAPI)!=null)
	                         revenueType=(String)lineObj.getSObject('Product2').get(productRevenueTypeAPI);
	                    
	                        
	                        if(setRevenueType.contains(revenueType) && mapRegimeCount.containsKey(revenueType+'#'+get15DigitId(lineObj.Product2Id))){
	                            Integer monthDiff=mapRegimeCount.get(revenueType+'#'+get15DigitId(lineObj.Product2Id));
	                              
	                            for(Integer i=0;i<monthDiff;i++){
				                	
				                Decimal productnumberPercent=0;
				                
				                if(mapCMPercentage.containskey(revenueType+'#'+get15DigitId(lineObj.Product2Id)+'#M+'+productNumber)){
				                	productnumberPercent=mapCMPercentage.get(revenueType+'#'+get15DigitId(lineObj.Product2Id)+'#M+'+productNumber);
				                }
				                Decimal productAmout=(totalLineItemAmount*	productnumberPercent)/100;	
				                	String monthStr='';
				                	if(monthPro==13){
				                		yearPro++;
				                		monthPro=1;
				                	}
				                	if(monthPro<10){
				                		monthStr='0'+monthPro;
				                	}
				                	else{
				                		monthStr=String.valueOf(monthPro);
				                	}
				                	
				                	String periodName='FY'+yearPro+'P'+monthStr;
				                	
									if(mapPeriodNameVsMOdel.containsKey(periodName)){
										FCST_Opportunity_Initial_Forecast__c pmObj=mapPeriodNameVsMOdel.get(periodName);
										if(pmObj.FCST_Product_Revenue__c==null)
											pmObj.FCST_Product_Revenue__c=0;
											
											
										pmObj.FCST_Product_Revenue__c=pmObj.FCST_Product_Revenue__c+productAmout;
									}
									
									else{
					                	FCST_Opportunity_Initial_Forecast__c pmForecastObj = new FCST_Opportunity_Initial_Forecast__c();
					                	pmForecastObj.FCST_Planning_Version__c =lstMPlanningversion[0].Id;
					                	if(mapPeriodNameVsPeriodObj.containsKey(periodName)){
					                		pmForecastObj.Fcst_Fiscal_Period__c=mapPeriodNameVsPeriodObj.get(periodName).Id;
					                	}
					                	pmForecastObj.Fcst_Opportunity__c=oppObj.Id;
					                	if(oppQhash!=null){
					                		pmForecastObj.Fcst_Q__c=oppQhash;
					                	}
					                	pmForecastObj.FCST_Product_Revenue__c=productAmout;	
					                	
					                	newPMForecastModelList.add(pmForecastObj);
					                	mapPeriodNameVsMOdel.put(periodName,pmForecastObj);
									}
				                	monthPro++;
				                	productNumber++;
				                }    
	                                
	                        }
	                    }
	               if(newPMForecastModelList!=null && newPMForecastModelList.size()>0){
	               		for(FCST_Opportunity_Initial_Forecast__c pnObj:newPMForecastModelList){
	               			decimal totalAmount=0;
	               			if(pnObj.FCST_Transition_Revenue__c!=null)
	               				totalAmount+=pnObj.FCST_Transition_Revenue__c;
	               			if(pnObj.FCST_Service_Revenue__c!=null)	
	               				totalAmount+=pnObj.FCST_Service_Revenue__c;
	               			if(pnObj.FCST_Product_Revenue__c!=null)	
	               				totalAmount+=pnObj.FCST_Product_Revenue__c;
	               			
	               			pnObj.Fcst_Weighted_Revenue__c=totalAmount;
	               			pnObj.User_Adjusted_Revenue__c=totalAmount;
	               			
	               		}
	               } 
	                                            
	             insert newPMForecastModelList;   
	            }
	        }
	        
	        
	        
	            
	         if(productmodelList!=null && productmodelList.size()>0)
	         	delete productmodelList;       
           
        }catch(Exception e) {
            System.debug('The following exception has occurred:' + e.getMessage());
            System.debug('Line number: ' + e.getLineNumber()); 
          }     
            
    }
}