Compucom CCQA Org 100919/src/objects/FCST_Opportunity_Initial_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>FCST_Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Opportunity Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Opportunity_Initial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Fiscal Year</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipName>FCST_Oppy_Inicial_Forecasts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fcst_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Opportunity Initial Forecasts</relationshipLabel>
        <relationshipName>FCST_Oppy_Initial_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fcst_Weighted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fcst Weighted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User_Adjusted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Adjusted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>FCST Opportunity Initial Forecast</label>
    <nameField>
        <label>FCST Oppy Initial Forecast  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Opportunity Initial Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/FCST_Product_Model__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>FCST Product Models</relationshipLabel>
        <relationshipName>FCST_Product_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Adjusted_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>User Adjusted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weighted_Revenue__c</fullName>
        <label>Weighted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>FCST Product Model</label>
    <nameField>
        <displayFormat>PRM-{000000}</displayFormat>
        <label>FCST Product Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Product Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Mapping_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Fcst_Q__c</fullName>
        <label>Fcst Q#</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Mapping Setting</label>
</CustomObject>

Compucom CCQA Org 100919/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FCST_Q__c</fullName>
        <displayFormat>Q-{0000}</displayFormat>
        <label>FCST Q#</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Compucom CCQA/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipLabel>FCST Planning Versions</relationshipLabel>
        <relationshipName>FCST_Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Compucom CCQA Org 100919/src/classes/FCST_Product_Model_Trigger_Util.cls
/****
  Developer Name/Author:  Pritam Gupta
  Created Date: 9-Sep-2019
  Work item number from JIRA:-CRN-173
  Description: we are now creating PM forecast and deleting Product model using Opporunity trigger and util class is-FCST_PM_Forecast_Util.

****/

public with sharing class FCST_Product_Model_Trigger_Util {
    
    
    public static void AddOpporunityInitailModels(set<Id> setOppIds,Set<Id> SetfiscalPeriodId,Set<Id> SetPlanningVersionId,List<FCST_Product_Model__c> planningModelList){
    /*    try{
         Map<String,Double> mapOppPVPPVsWeigthedAmount =new Map<String,Double>();
         Map<String,Double> mapOppPVPPVsUserAdjustedAmount =new Map<String,Double>();
        Map<String,FCST_Opportunity_Initial_Forecast__c> mapintialForecastVsWeigthedAmount =new Map<String,FCST_Opportunity_Initial_Forecast__c>(); 
        List<FCST_Opportunity_Initial_Forecast__c> upsertIntialForecastList = new List<FCST_Opportunity_Initial_Forecast__c>();
        String closedString='Closed Won';
        Mapping_Setting__c mapCustomObj=Mapping_Setting__c.getValues('FCST Mapping Data');
        string planningModelQFieldApi=mapCustomObj.Fcst_Q__c;
        planningModelQFieldApi=planningModelQFieldApi.replace('', '');
        planningModelQFieldApi=planningModelQFieldApi.trim();
        String relatedField='Opportunity__r.'+planningModelQFieldApi;
        
        
        String planningModelQuery='Select User_Adjusted_Revenue__c,'+relatedField+',Name,Fiscal_Period__c,Opportunity__c,Planning_Version__c,Weighted_Revenue__c,Id from FCST_Product_Model__c where Opportunity__c IN:setOppIds and Fiscal_Period__c IN: SetfiscalPeriodId and Planning_Version__c IN:SetPlanningVersionId and Opportunity__r.StageName=:closedString';
        
         List<FCST_Product_Model__c> allPlanningModelList=database.query(planningModelQuery);
        List<FCST_Opportunity_Initial_Forecast__c> allIntialForecast= [Select User_Adjusted_Revenue__c,Id,Fcst_Fiscal_Period__c,Fcst_Q__c,Fcst_Weighted_Revenue__c,Fcst_Opportunity__c,FCST_Planning_Version__c  from FCST_Opportunity_Initial_Forecast__c   where Fcst_Opportunity__c IN:setOppIds and Fcst_Fiscal_Period__c IN: SetfiscalPeriodId and FCST_Planning_Version__c IN:SetPlanningVersionId  ];
        
        
        if(allPlanningModelList!=null && allPlanningModelList.size()>0){
              for(FCST_Product_Model__c planningObj:allPlanningModelList){
                String qNumber=(String)planningObj.getSObject('Opportunity__r').get(planningModelQFieldApi);
                double totalVal=0,userAdjustedAmount=0;
                  if(mapOppPVPPVsWeigthedAmount.containsKey(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber)){ 
                     double amount =mapOppPVPPVsWeigthedAmount.get(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber);
                     totalVal=amount+planningObj.Weighted_Revenue__c;
                     mapOppPVPPVsWeigthedAmount.put(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber,totalVal);
                   }
                  else{
                     mapOppPVPPVsWeigthedAmount.put(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber,planningObj.Weighted_Revenue__c);
                  }
                  
                  if(mapOppPVPPVsUserAdjustedAmount.containsKey(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber)){ 
                     double amount =mapOppPVPPVsUserAdjustedAmount.get(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber);
                     userAdjustedAmount=amount+planningObj.User_Adjusted_Revenue__c;
                     mapOppPVPPVsUserAdjustedAmount.put(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber,totalVal);
                   }
                  else{
                     mapOppPVPPVsUserAdjustedAmount.put(planningObj.Opportunity__c+'#'+planningObj.Planning_Version__c+'#'+planningObj.Fiscal_Period__c+'#'+qNumber,planningObj.User_Adjusted_Revenue__c);
                  }
            }  
         }
        if(allIntialForecast!=null && allIntialForecast.size()>0){
            for(FCST_Opportunity_Initial_Forecast__c intialObj:allIntialForecast){
                mapintialForecastVsWeigthedAmount.put(intialObj.Fcst_Opportunity__c+'#'+intialObj.FCST_Planning_Version__c+'#'+intialObj.Fcst_Fiscal_Period__c+'#'+intialObj.Fcst_Q__c,intialObj);
            }
         }
         
         for(String keyObj:mapOppPVPPVsWeigthedAmount.keyset()){
             double amountVal=mapOppPVPPVsWeigthedAmount.get(keyObj);
             double userAdjustedAmount=mapOppPVPPVsUserAdjustedAmount.get(keyObj);
             
             if(userAdjustedAmount==null) userAdjustedAmount=0;
             if(amountVal==null) amountVal=0;
             
             if(mapintialForecastVsWeigthedAmount.containsKey(keyObj) ){
                FCST_Opportunity_Initial_Forecast__c obj=mapintialForecastVsWeigthedAmount.get(keyObj);
                obj.Fcst_Weighted_Revenue__c=amountVal;
                obj.User_Adjusted_Revenue__c=userAdjustedAmount;
                upsertIntialForecastList.add(obj);
             }
             else{
                FCST_Opportunity_Initial_Forecast__c forecastInitialObj = new FCST_Opportunity_Initial_Forecast__c();
                List<String> idParts = keyObj.split('#');
                forecastInitialObj.Fcst_Opportunity__c=Id.valueOf(idParts[0]);
               forecastInitialObj.FCST_Planning_Version__c=Id.valueOf(idParts[1]);
                forecastInitialObj.Fcst_Fiscal_Period__c=Id.valueOf(idParts[2]);
                forecastInitialObj.Fcst_Q__c=idParts[3];
                forecastInitialObj.Fcst_Weighted_Revenue__c=amountVal;
                forecastInitialObj.User_Adjusted_Revenue__c=userAdjustedAmount;
                upsertIntialForecastList.add(forecastInitialObj);
             }
         }
         
         if(upsertIntialForecastList!=null && upsertIntialForecastList.size()>0){
            upsert upsertIntialForecastList;
         }
         System.debug('Line setOppIds: ' + setOppIds);
         if(setOppIds!=null && setOppIds.size()>0){ 
	         FCST_To_CleanModel uca = new FCST_To_CleanModel(setOppIds);
	         Database.executeBatch(uca);
         }
    	}
    
    
    
          catch(Exception e) {
            System.debug('The following exception has occurred:aa ' + e.getMessage());
            System.debug('Line number: ' + e.getLineNumber()); 
          }
         */ 
    }
    
    
   
    
    
    
    
}